packages:
  - adminstration
  - storefront-api
  - storefront
  - storefront-new
  - packages/*

allowBuilds:
  '@parcel/watcher': false
  '@sentry/cli': true
  '@swc/core': false
  core-js: false
  esbuild: false
  msgpackr-extract: true
  msw: false
  sharp: false
  unrs-resolver: false
