export const analyticsCopyAr = {
  loading: 'جارٍ تحديث العرض…',
  updated: 'آخر تحديث',
  refresh: 'تحديث',
  apply: 'تطبيق',
  cancel: 'إلغاء',
  close: 'إغلاق',
  save: 'حفظ',
  delete: 'حذف',
  reset: 'إعادة للوضع التلقائي',
  export: 'تصدير CSV',
  syncMeta: 'مزامنة نطاق Meta',
  syncing: 'جارٍ المزامنة…',
  inspect: 'تفاصيل',
  compare: 'مقارنة',
  previousPeriod: 'مقارنة بالفترة السابقة',
  noComparison: 'لا توجد فترة سابقة',
  noData: 'لا توجد بيانات موثوقة لهذا الاختيار.',
  partialPeriod: 'فترة مفتوحة',
  exactRows: 'القيم الدقيقة',
  sourceHealth: 'مصادر البيانات',
  sourceNote: 'التغطية جزء من المقياس وليست ملاحظة جانبية.',
  ranges: {
    '7d': '7 أيام',
    '14d': '14 يومًا',
    '30d': '30 يومًا',
    '90d': '90 يومًا',
    year: 'السنة',
    all: 'الكل',
    custom: 'مخصص',
  },
  grains: { auto: 'تلقائي', day: 'يومي', week: 'أسابيع الجمعة', month: 'شهري' },
  metrics: {
    trueProfit: 'الربح الحقيقي',
    profitX: 'مضاعف الربح',
    grossProfit: 'الربح الخام',
    adjustedProfit: 'الربح المعدل',
    automaticPaidProfit: 'ربح الطلبات المدفوعة',
    paidProfitCoverage: 'تغطية تكلفة الطلبات المدفوعة',
    adCost: 'تكلفة Meta',
    postedOrders: 'الطلبات المرسلة',
    postedUnits: 'الوحدات المرسلة',
    paidUnits: 'الوحدات المدفوعة',
    costPerPosted: 'تكلفة / مرسلة',
    costPerDelivered: 'تكلفة / مسلمة',
    costPerPaid: 'تكلفة / مدفوعة',
    submittedOrders: 'الطلبات المسجلة',
    paidOrders: 'الطلبات المدفوعة',
    storefrontConversion: 'تحويل المتجر',
    impressions: 'مرات الظهور',
    outboundClicks: 'النقرات الصادرة',
    landingPageViews: 'زيارات الهبوط',
    activeShipments: 'الشحنات النشطة',
    observedReturnRate: 'نسبة الإرجاع الناضجة',
    sessions: 'الجلسات',
    engagementRate: 'التفاعل',
    purchases: 'الطلبات المسجلة',
    conversionRate: 'التحويل',
    errorRate: 'نسبة الأخطاء',
    returningJourneys: 'الزيارات المتكررة',
    productProfit: 'مرجع ربح التسوية',
    unitsSold: 'الوحدات المباعة',
    customers: 'العملاء',
    repeatRate: 'نسبة التكرار',
    activeMonthlyBurn: 'التكلفة الشهرية',
    periodOperatingCost: 'تكاليف الفترة',
    manualOverrideDays: 'أيام معدلة',
    projectedCoverage: 'تغطية التكلفة',
    searchClicks: 'نقرات Google',
    searchImpressions: 'مرات الظهور في البحث',
    searchCtr: 'نسبة النقر',
    averagePosition: 'متوسط الترتيب',
  },
  sections: {
    trajectory: 'مسار النشاط',
    signals: 'قائمة المتابعة',
    commerceFunnel: 'نضج الطلبات',
    cashPipeline: 'مسار السيولة',
    paidEconomics: 'اقتصاد الدفع التلقائي',
    reconciliation: 'مرجع التسوية',
    forecast: 'النظرة المستقبلية',
    moneyPerformance: 'الأداء المالي',
    weeklyEconomics: 'أسابيع تبدأ الجمعة',
    economicsLedger: 'السجل المالي',
    profitEfficiency: 'كفاءة الربح',
    creativeFatigue: 'إجهاد الإعلانات',
    creativeResponse: 'استجابة المحتوى',
    paidFunnel: 'قمع الإعلانات',
    hierarchy: 'هيكل الحملات',
    trackingHealth: 'سلامة التتبع',
    deliveryPipeline: 'مسار التوصيل',
    shipmentStates: 'حالات الشحن',
    exceptionQueue: 'قائمة الاستثناءات',
    cycleTime: 'زمن الدورة',
    attempts: 'المحاولات والنتيجة',
    cohorts: 'أفواج الطلبات المرسلة',
    siteTrend: 'اتجاه المتجر',
    searchTrend: 'الطلب عبر البحث',
    searchOpportunities: 'قائمة الفرص',
    searchPages: 'ظهور صفحات الهبوط',
    searchMix: 'مزيج الاكتشاف',
    indexHealth: 'صحة الفهرسة',
    siteFunnel: 'قمع المتجر',
    paths: 'المسارات الحديثة',
    searches: 'طلب البحث',
    landingPages: 'صفحات الهبوط',
    experience: 'جودة التجربة',
    products: 'ذكاء المنتجات',
    basketPairs: 'منتجات تشترى معًا',
    geography: 'المناطق والتوصيل',
    customerBase: 'قاعدة العملاء',
    planningReturns: 'نسبة الإرجاع المخططة',
    operatingCosts: 'تكاليف التشغيل',
    dailyOverrides: 'التعديلات اليومية',
    formula: 'المعادلة الأساسية',
    automationEvidence: 'الأتمتة مقابل التسويات',
  },
  sources: {
    orders: 'الطلبات',
    ecotrack: 'EcoTrack',
    meta: 'Meta',
    storefront: 'المتجر',
    searchConsole: 'بحث Google',
    settlements: 'التسويات',
    assumptions: 'افتراضات يدوية',
  },
  sourceStates: {
    live: 'مباشر',
    current: 'حالي',
    lagged: 'متأخر',
    manual: 'يدوي',
    partial: 'جزئي',
    missing: 'مفقود',
  },
  signalLabels: {
    belowBreakEven: 'مضاعف الربح دون نقطة التعادل',
    aboveBreakEven: 'مضاعف الربح فوق نقطة التعادل',
    returnAssumptionGap: 'المرتجعات المرصودة تختلف عن التخطيط',
    costCoverageGap: 'بيانات تكلفة الشراء غير مكتملة',
    fridayPending: 'إنفاق الجمعة ينتظر الترحيل',
    activePipeline: 'طلبات ما زالت في مسار التوصيل',
  },
  warningLabels: {
    sourceMissing: 'مصدر مفقود لهذه الفترة',
    sourcePartial: 'مصدر يغطي جزءًا فقط من الفترة',
    projectedCostCoverage: 'الربح المتوقع يستخدم هامشًا احتياطيًا بنسبة 30٪',
    pendingFridayRollforward: 'إنفاق Meta للجمعة ينتظر الترحيل',
    pathRetentionPartial: 'تفاصيل المسارات محدودة بمدة الاحتفاظ بالأحداث',
    searchDetailCoverage: 'تفاصيل الاستعلام والصفحة محدودة بخصوصية Google',
  },
  columns: {
    date: 'التاريخ',
    value: 'القيمة',
    status: 'الحالة',
    orders: 'الطلبات',
    spend: 'الإنفاق',
    profit: 'الربح',
    trueProfit: 'الربح الحقيقي',
    profitX: 'مضاعف الربح',
    operatingCost: 'تكاليف التشغيل',
    grossProfit: 'الربح الخام',
    adjustedProfit: 'الربح المعدل',
    adCost: 'تكلفة الإعلان',
    netProfit: 'صافي الربح',
    coverage: 'التغطية',
    name: 'الاسم',
    campaign: 'الحملة',
    impressions: 'الظهور',
    ctr: 'CTR',
    outboundCtr: 'CTR الصادر',
    cpm: 'CPM',
    landingViews: 'زيارات الهبوط',
    videoCompletion: 'اكتمال الفيديو',
    watchTime: 'متوسط المشاهدة',
    ranking: 'الترتيب',
    confirmed: 'مؤكدة',
    posted: 'مرسلة',
    paid: 'مدفوعة',
    returned: 'مرتجعة',
    costPerPosted: 'تكلفة / مرسلة',
    share: 'الحصة',
    stale: 'متوقفة >48س',
    age: 'متوسط العمر',
    p50: 'الوسيط',
    p75: 'P75',
    p90: 'P90',
    sample: 'العينة',
    sessions: 'الجلسات',
    conversion: 'التحويل',
    views: 'المشاهدات',
    carts: 'السلات',
    revenue: 'الإيراد',
    units: 'الوحدات',
    margin: 'الهامش',
    category: 'الفئة',
    brand: 'العلامة',
    first: 'الأول',
    second: 'الثاني',
    repeat: 'التكرار',
    source: 'المصدر',
    note: 'ملاحظة',
    query: 'عبارة البحث',
    page: 'الصفحة',
    clicks: 'النقرات',
    position: 'الترتيب',
    potential: 'نقرات محتملة',
    device: 'الجهاز',
    country: 'الدولة',
  },
  labels: {
    ecoTrackFee: 'رسوم EcoTrack',
    paidCod: 'تحصيل مدفوع',
    estimatedFees: 'الرسوم المقدرة',
    netRecovered: 'الصافي المحصل',
    cod: 'التحصيل',
    fees: 'الرسوم',
    providerCod: 'تحصيل شركة التوصيل',
    profitMaturation: 'نضج الربح',
    projectedTrueProfit: 'الربح الحقيقي المتوقع',
    deliveredTrueProfit: 'الربح الحقيقي المسلّم',
    paidTrueProfit: 'الربح الحقيقي المدفوع',
    postingWeek: 'أسبوع النشر',
    posted: 'منشورة',
    delivered: 'مسلّمة',
    paid: 'مدفوعة',
    projected: 'متوقع',
    paidProfit: 'الربح المدفوع',
    variance: 'الفرق',
    maturity: 'النضج',
    open: 'مفتوح',
    upper: 'الحد الأعلى',
    lower: 'الحد الأدنى',
    beforeReturns: 'قبل المرتجعات',
    afterReturns: 'بعد المرتجعات',
    playRate: 'معدل التشغيل',
    completion: 'الإكمال',
    averageWatch: 'متوسط المشاهدة',
    outboundCtr: 'معدل النقر الخارجي',
    confirmationRate: 'معدل التأكيد',
    clickToPage: 'النقرة ← الصفحة',
    metaPurchases: 'مشتريات Meta',
    firstPartyOrders: 'طلبات الطرف الأول',
    exactAdIdCoverage: 'تغطية معرّفات الإعلانات الدقيقة',
    outcomeMaturity: 'نضج النتائج',
    campaignMaturation: 'نضج الحملات',
    costPerPosted: 'التكلفة / منشورة',
    costPerDelivered: 'التكلفة / مسلّمة',
    costPerPaid: 'التكلفة / مدفوعة',
    metaSpend: 'إنفاق Meta',
    adCostDzd: 'تكلفة الإعلان DZD',
    outcomeWindowCost: 'تكلفة نافذة النتائج',
    outcomeSpendCoverage: 'تغطية إنفاق النتائج',
    impressions: 'مرات الظهور',
    outboundClicks: 'النقرات الخارجية',
    uniqueOutbound: 'النقرات الخارجية الفريدة',
    landingViews: 'مشاهدات صفحة الوصول',
    landingViewRate: 'معدل مشاهدة صفحة الوصول',
    videoPlays: 'تشغيلات الفيديو',
    videoCompletion: 'إكمال الفيديو',
    qualityRanking: 'ترتيب الجودة',
    engagementRanking: 'ترتيب التفاعل',
    conversionRanking: 'ترتيب التحويل',
    bricOrders: 'طلبات Bric',
    confirmed: 'مؤكدة',
    returned: 'مرتجعة',
    projectedProfitX: 'الربح × المتوقع',
    paidProfitX: 'الربح × المدفوع',
    profitCoverage: 'تغطية الربح',
    manualModelInput: 'مدخل يدوي للنموذج',
    active: 'نشطة',
    errors: 'أخطاء',
    productViewToCartSessions: 'عرض المنتج ← السلة',
    checkoutToSubmittedOrder: 'الدفع ← الطلب المرسل',
    from: 'من',
    to: 'إلى',
    aiAssistedShopping: 'تسوق بمساعدة الذكاء الاصطناعي',
    opens: 'مرات الفتح',
    messages: 'الرسائل',
    resultClicks: 'نقرات النتائج',
    influencedOrders: 'الطلبات المتأثرة',
    opportunity: 'الفرصة',
    searchLandingPagesDescription:
      'صفحات الوصول كما يراها Google. اختر صفًا لمراجعة عبارات البحث التي تمنحها الظهور.',
    queries: 'عبارات البحث',
    devices: 'الأجهزة',
    countries: 'الدول',
    sitemap: 'خريطة الموقع',
    inspectedSample: 'العينة المفحوصة',
    searchOpportunityEvidence: 'أدلة فرصة البحث',
    currentCtr: 'معدل النقر الحالي',
    comparableCtr: 'معدل النقر المقارن',
    googleLandingPageEvidence: 'أدلة Google لصفحة الوصول',
    productViews: 'مشاهدات المنتج',
    terminalPaid: 'مدفوعة نهائيًا',
    paidReturned: 'مدفوعة / مرتجعة',
    stillActive: 'ما زالت نشطة',
    scatterViews: 'المشاهدات ←',
    scatterPaidOutcome: 'النتيجة المدفوعة ↑',
    bubbleResolvedOrders: 'الفقاعة · الطلبات المحسومة',
    terminalPaidRate: 'معدل الدفع النهائي',
    postedUnits: 'الوحدات المنشورة',
    projectedContribution: 'المساهمة المتوقعة',
    delivery: 'التوصيل',
    wilaya: 'الولاية',
    attempts: 'المحاولات',
    pipelineCod: 'التحصيل الجاري',
    commune: 'البلدية',
    customers: 'العملاء',
    customer: 'العميل',
    city: 'المدينة',
    submitted: 'مرسلة',
    paidRevenue: 'الإيراد المدفوع',
    contribution: 'المساهمة',
    margin: 'الهامش',
    postedOrders: 'الطلبات المنشورة',
    paidOrders: 'الطلبات المدفوعة',
    returnedOrders: 'الطلبات المرتجعة',
    costCoverage: 'تغطية التكلفة',
    medianDelivery: 'وسيط مدة التوصيل',
    units: 'الوحدات',
    economicControls: 'الإعدادات الاقتصادية',
    period: 'الفترة',
    returnPercent: 'الإرجاع %',
    blankFieldsDefer: 'تعود الحقول الفارغة كلٌ على حدة إلى المصدر التلقائي.',
    orders: 'طلبات',
    terminal: 'نهائية',
    eligible: 'مؤهلة',
    resolved: 'محسومة',
    postingCohorts: 'مجموعات النشر',
    terminalOrders: 'طلبات نهائية',
    metaInsightsSynchronized: 'تمت مزامنة بيانات Meta.',
    googleSearchSynchronized: 'تمت مزامنة بيانات بحث Google.',
    syncFailed: 'فشلت المزامنة.',
    syncGoogle: 'مزامنة Google',
    played: 'تم تشغيله',
    completed: 'مكتمل',
    outcomeWindow: 'نافذة النتائج',
    events: 'أحداث',
    unavailable: 'غير متاح',
    failed: 'فاشل',
    noEvent: 'لا حدث',
    rawEventWindow: 'نافذة الأحداث الخام',
    empty: '(فارغ)',
    zeroResultsShort: 'بدون نتائج',
    samples: 'عينات',
    poor: 'ضعيفة',
    sessions: 'جلسات',
    clicks: 'نقرات',
    position: 'الترتيب',
    rankingPages: 'صفحات مرتبة',
    brand: 'علامة',
    discovery: 'اكتشاف',
    nearPageOne: 'قريبة من الصفحة الأولى',
    ctrGap: 'فجوة معدل النقر',
    contentGap: 'فجوة محتوى',
    searchAppearance: 'مظهر البحث',
    urls: 'روابط',
    warnings: 'تحذيرات',
    downloaded: 'آخر تنزيل',
    noUrlsInspected: 'لم يتم فحص أي رابط',
    pagesNeedReview: 'صفحات تحتاج مراجعة',
    noActionableIssue: 'لا توجد مشكلة قابلة للإجراء في العينة الحالية',
    openPublicPage: 'فتح الصفحة العامة',
    searchProduct: 'ابحث عن منتج أو SKU أو فئة',
    above: 'أعلى',
    below: 'أدنى',
    insufficientProductOutcomes: 'لا توجد نتائج منتجات محسومة كافية لمقارنة موثوقة.',
    noSku: 'بدون SKU',
    uncategorized: 'بدون فئة',
    metaReportedRegions: 'المناطق المبلّغ عنها من Meta',
    aggregateMediaGeography: 'جغرافيا إعلامية مجمعة · غير مرتبطة بولايات العملاء',
    untracked: 'غير متتبعة',
    provider: 'شركة التوصيل',
    secondOrderConversion: 'التحويل إلى الطلب الثاني',
    exactMetaAssociations: 'روابط Meta الدقيقة',
    unknownCampaign: 'حملة غير معروفة',
    unknownAdSet: 'مجموعة إعلانية غير معروفة',
    noExactAdAssociation: 'لا يوجد ارتباط دقيق بمعرّف إعلان في هذا النطاق.',
    periodChange: 'تغير الفترة',
    assumptionsSaved: 'تم حفظ الافتراضات.',
    operatingCostUpdated: 'تم تحديث تكلفة التشغيل.',
    operatingCostAdded: 'تمت إضافة تكلفة التشغيل.',
    operatingCostRemoved: 'تم حذف تكلفة التشغيل.',
    dailyOverrideSaved: 'تم حفظ التعديل اليومي.',
    dailyValuesReset: 'عادت القيم اليومية إلى المصادر التلقائية.',
    cpmEur: 'CPM EUR',
    analyticsRange: 'نطاق التحليلات',
    analyticsGrain: 'تجميع التحليلات',
    startDate: 'تاريخ البدء',
    endDate: 'تاريخ النهاية',
    analyticsRequestFailed: 'فشل طلب التحليلات.',
    productViewSessions: 'جلسات مشاهدة المنتج',
    cartSessions: 'جلسات السلة',
    checkoutSessions: 'جلسات الدفع',
    submittedOrderSessions: 'جلسات الطلبات المرسلة',
    nextSevenDayModel: 'نموذج الأيام السبعة القادمة',
  },
  modes: {
    projected: 'متوقع',
    realized: 'مدفوع فعلي',
    cumulative: 'تراكمي',
    daily: 'يومي',
    campaign: 'الحملات',
    adset: 'المجموعات',
    ad: 'الإعلانات',
  },
  cashStages: {
    submitted: 'مُرسلة · غير مؤكدة',
    confirmed: 'مؤكدة · غير منشورة',
    inTransit: 'قيد النقل',
    deliveredAwaitingCollection: 'تم التسليم · بانتظار التحصيل',
    collectedAwaitingPayout: 'تم التحصيل · بانتظار الدفع',
    paymentReady: 'الدفع جاهز',
    paid: 'مدفوع ومؤرشف',
  },
  fulfillmentPhases: {
    paid: 'مدفوعة',
    return: 'مرتجعة',
    cancelled: 'ملغاة',
    cash: 'بانتظار الدفع',
    delivery: 'قيد التوصيل',
    transit: 'قيد النقل',
    ready: 'جاهزة للشحن',
    exception: 'تحتاج مراجعة',
    untracked: 'غير متتبعة',
  },
  expectedToPost: 'متوقع نشرها',
  returnCopy: {
    planning: 'نسبة التخطيط',
    mature: 'المرصود الناضج',
    terminal: 'كل النتائج النهائية',
    useMature: 'استخدام النسبة الناضجة',
    useTerminal: 'استخدام كل النتائج',
    caveat: 'يظهر التاريخ المرصود كدليل ولا يغيّر نسبة التخطيط إلا باختيارك.',
  },
  assumptions: {
    fx: 'سعر EUR → DZD',
    defaultReturn: 'نسبة الإرجاع الافتراضية',
    restFrom: 'بدء راحة الجمعة',
    newCost: 'إضافة تكلفة',
    monthly: 'شهري',
    once: 'مرة واحدة',
    amount: 'المبلغ DZD',
    start: 'تاريخ البدء',
    end: 'تاريخ النهاية (اختياري)',
    newOverride: 'تعديل اليوم',
    gross: 'الربح الخام DZD',
    confirmed: 'الطلبات المؤكدة',
    returnRate: 'نسبة الإرجاع %',
    notes: 'ملاحظة المشغل',
    automatic: 'تلقائي',
    default: 'افتراضي',
    manual: 'يدوي',
    missing: 'مفقود',
  },
} as const;
