export const analyticsCopyEn = {
  loading: 'Updating this view…',
  updated: 'Updated',
  refresh: 'Refresh',
  apply: 'Apply',
  cancel: 'Cancel',
  close: 'Close',
  save: 'Save',
  delete: 'Delete',
  reset: 'Reset to automatic',
  export: 'Export CSV',
  syncMeta: 'Sync Meta range',
  syncing: 'Synchronizing…',
  inspect: 'Inspect',
  compare: 'Compare',
  previousPeriod: 'vs previous period',
  noComparison: 'No comparable period',
  noData: 'No trustworthy data for this selection.',
  partialPeriod: 'Open period',
  exactRows: 'Exact values',
  sourceHealth: 'Data sources',
  sourceNote: 'Coverage is part of the metric, not a footnote.',
  ranges: {
    '7d': '7 days',
    '14d': '14 days',
    '30d': '30 days',
    '90d': '90 days',
    year: 'Year',
    all: 'All',
    custom: 'Custom',
  },
  grains: { auto: 'Auto grain', day: 'Daily', week: 'Friday weeks', month: 'Monthly' },
  metrics: {
    trueProfit: 'True profit',
    profitX: 'Profit ×',
    grossProfit: 'Gross profit',
    adjustedProfit: 'Adjusted profit',
    automaticPaidProfit: 'Paid-order profit',
    paidProfitCoverage: 'Exact paid-cost coverage',
    adCost: 'Meta cost',
    postedOrders: 'Posted orders',
    postedUnits: 'Posted units',
    paidUnits: 'Paid units',
    costPerPosted: 'Cost / posted',
    costPerDelivered: 'Cost / delivered',
    costPerPaid: 'Cost / paid',
    submittedOrders: 'Submitted orders',
    paidOrders: 'Paid orders',
    storefrontConversion: 'Store conversion',
    impressions: 'Impressions',
    outboundClicks: 'Outbound clicks',
    landingPageViews: 'Landing views',
    activeShipments: 'Active shipments',
    observedReturnRate: 'Mature return rate',
    sessions: 'Sessions',
    engagementRate: 'Engagement',
    purchases: 'Orders placed',
    conversionRate: 'Conversion',
    errorRate: 'Error rate',
    returningJourneys: 'Returning journeys',
    productProfit: 'Settlement profit reference',
    unitsSold: 'Units sold',
    customers: 'Customers',
    repeatRate: 'Repeat rate',
    activeMonthlyBurn: 'Monthly burn',
    periodOperatingCost: 'Period operating cost',
    manualOverrideDays: 'Override days',
    projectedCoverage: 'Cost coverage',
    searchClicks: 'Google clicks',
    searchImpressions: 'Search impressions',
    searchCtr: 'Search CTR',
    averagePosition: 'Average position',
  },
  sections: {
    trajectory: 'Profit',
    signals: 'Signals',
    commerceFunnel: 'Order maturity',
    cashPipeline: 'Cash pipeline',
    paidEconomics: 'Paid economics',
    reconciliation: 'Settlement reference',
    forecast: 'Forward view',
    moneyPerformance: 'Financial performance',
    weeklyEconomics: 'Friday-start weeks',
    economicsLedger: 'Economics ledger',
    profitEfficiency: 'Profit efficiency',
    creativeFatigue: 'Creative fatigue',
    creativeResponse: 'Creative response',
    paidFunnel: 'Paid funnel',
    hierarchy: 'Campaign hierarchy',
    trackingHealth: 'Tracking health',
    deliveryPipeline: 'Delivery pipeline',
    shipmentStates: 'Shipment states',
    exceptionQueue: 'Exception queue',
    cycleTime: 'Cycle time',
    attempts: 'Attempts versus outcome',
    cohorts: 'Posted-order cohorts',
    siteTrend: 'Storefront trend',
    searchTrend: 'Search demand',
    searchOpportunities: 'Opportunity queue',
    searchPages: 'Landing-page visibility',
    searchMix: 'Discovery mix',
    indexHealth: 'Index health',
    siteFunnel: 'Storefront funnel',
    paths: 'Recent paths',
    searches: 'Search demand',
    landingPages: 'Landing pages',
    experience: 'Experience quality',
    products: 'Product intelligence',
    basketPairs: 'Products bought together',
    geography: 'Geography and delivery',
    customerBase: 'Customer base',
    planningReturns: 'Planning return rate',
    operatingCosts: 'Operating costs',
    dailyOverrides: 'Daily source overrides',
    formula: 'Canonical formula',
    automationEvidence: 'Automation versus settlement evidence',
  },
  sources: {
    orders: 'Orders',
    ecotrack: 'EcoTrack',
    meta: 'Meta',
    storefront: 'Storefront',
    searchConsole: 'Google Search',
    settlements: 'Settlements',
    assumptions: 'Manual assumptions',
  },
  sourceStates: {
    live: 'Live',
    current: 'Current',
    lagged: 'Lagged',
    manual: 'Manual',
    partial: 'Partial',
    missing: 'Missing',
  },
  signalLabels: {
    belowBreakEven: 'Profit × is below break-even',
    aboveBreakEven: 'Profit × is above break-even',
    returnAssumptionGap: 'Observed returns differ from planning',
    costCoverageGap: 'Purchase-cost snapshots are incomplete',
    fridayPending: 'Friday spend awaits roll-forward',
    activePipeline: 'Orders are still moving through delivery',
  },
  warningLabels: {
    sourceMissing: 'A source is missing for this range',
    sourcePartial: 'A source only covers part of this range',
    projectedCostCoverage: 'Projected profit uses a 30% fallback margin for missing costs',
    pendingFridayRollforward: 'Friday Meta spend is pending roll-forward',
    pathRetentionPartial: 'Path detail is limited by raw-event retention',
    searchDetailCoverage: 'Query and page detail is privacy-limited by Google',
  },
  columns: {
    date: 'Date',
    value: 'Value',
    status: 'Status',
    orders: 'Orders',
    spend: 'Spend',
    profit: 'Profit',
    trueProfit: 'True profit',
    profitX: 'Profit ×',
    operatingCost: 'Operating costs',
    grossProfit: 'Gross profit',
    adjustedProfit: 'Adjusted profit',
    adCost: 'Ad cost',
    netProfit: 'Net profit',
    coverage: 'Coverage',
    name: 'Name',
    campaign: 'Campaign',
    impressions: 'Impressions',
    ctr: 'CTR',
    outboundCtr: 'Outbound CTR',
    cpm: 'CPM',
    landingViews: 'Landing views',
    videoCompletion: 'Video complete',
    watchTime: 'Avg watch',
    ranking: 'Ranking',
    confirmed: 'Confirmed',
    posted: 'Posted',
    paid: 'Paid',
    returned: 'Returned',
    costPerPosted: 'Cost / posted',
    share: 'Share',
    stale: 'Stale >48h',
    age: 'Median age',
    p50: 'Median',
    p75: 'P75',
    p90: 'P90',
    sample: 'Sample',
    sessions: 'Sessions',
    conversion: 'Conversion',
    views: 'Views',
    carts: 'Carts',
    revenue: 'Revenue',
    units: 'Units',
    margin: 'Margin',
    category: 'Category',
    brand: 'Brand',
    first: 'First',
    second: 'Second',
    repeat: 'Repeat',
    source: 'Source',
    note: 'Note',
    query: 'Query',
    page: 'Page',
    clicks: 'Clicks',
    position: 'Position',
    potential: 'Potential clicks',
    device: 'Device',
    country: 'Country',
  },
  labels: {
    ecoTrackFee: 'EcoTrack fee',
    paidCod: 'Paid COD',
    estimatedFees: 'Estimated fees',
    netRecovered: 'Net recovered',
    cod: 'COD',
    fees: 'Fees',
    providerCod: 'Provider COD',
    profitMaturation: 'Profit maturation',
    projectedTrueProfit: 'Projected true profit',
    deliveredTrueProfit: 'Delivered true profit',
    paidTrueProfit: 'Paid true profit',
    postingWeek: 'Posting week',
    posted: 'Posted',
    delivered: 'Delivered',
    paid: 'Paid',
    projected: 'Projected',
    paidProfit: 'Paid profit',
    variance: 'Variance',
    maturity: 'Maturity',
    open: 'Open',
    upper: 'Upper',
    lower: 'Lower',
    beforeReturns: 'Before returns',
    afterReturns: 'After returns',
    playRate: 'Play rate',
    completion: 'Completion',
    averageWatch: 'Average watch',
    outboundCtr: 'Outbound CTR',
    confirmationRate: 'Confirmation rate',
    clickToPage: 'Click → page',
    metaPurchases: 'Meta purchases',
    firstPartyOrders: 'First-party orders',
    exactAdIdCoverage: 'Exact ad-ID coverage',
    outcomeMaturity: 'Outcome maturity',
    campaignMaturation: 'Campaign maturation',
    costPerPosted: 'Cost / posted',
    costPerDelivered: 'Cost / delivered',
    costPerPaid: 'Cost / paid',
    metaSpend: 'Meta spend',
    adCostDzd: 'Ad cost DZD',
    outcomeWindowCost: 'Outcome-window cost',
    outcomeSpendCoverage: 'Outcome spend coverage',
    impressions: 'Impressions',
    outboundClicks: 'Outbound clicks',
    uniqueOutbound: 'Unique outbound',
    landingViews: 'Landing views',
    landingViewRate: 'Landing-view rate',
    videoPlays: 'Video plays',
    videoCompletion: 'Video completion',
    qualityRanking: 'Quality ranking',
    engagementRanking: 'Engagement ranking',
    conversionRanking: 'Conversion ranking',
    bricOrders: 'Bric orders',
    confirmed: 'Confirmed',
    returned: 'Returned',
    projectedProfitX: 'Projected Profit ×',
    paidProfitX: 'Paid Profit ×',
    profitCoverage: 'Profit coverage',
    manualModelInput: 'Manual model input',
    active: 'Active',
    errors: 'Errors',
    productViewToCartSessions: 'Product-view → cart sessions',
    checkoutToSubmittedOrder: 'Checkout → submitted order',
    from: 'From',
    to: 'To',
    aiAssistedShopping: 'AI-assisted shopping',
    opens: 'Opens',
    messages: 'Messages',
    resultClicks: 'Result clicks',
    influencedOrders: 'Influenced orders',
    opportunity: 'Opportunity',
    searchLandingPagesDescription:
      'Landing pages as Google sees them. Select a row to inspect the queries creating its visibility.',
    queries: 'Queries',
    devices: 'Devices',
    countries: 'Countries',
    sitemap: 'Sitemap',
    inspectedSample: 'Inspected sample',
    searchOpportunityEvidence: 'Search opportunity evidence',
    currentCtr: 'Current CTR',
    comparableCtr: 'Comparable CTR',
    googleLandingPageEvidence: 'Google landing-page evidence',
    productViews: 'Product views',
    terminalPaid: 'Terminal paid',
    paidReturned: 'Paid / returned',
    stillActive: 'Still active',
    scatterViews: 'Views →',
    scatterPaidOutcome: 'Paid outcome ↑',
    bubbleResolvedOrders: 'Bubble · resolved orders',
    terminalPaidRate: 'Terminal paid rate',
    postedUnits: 'Posted units',
    projectedContribution: 'Projected contribution',
    delivery: 'Delivery',
    wilaya: 'Wilaya',
    attempts: 'Attempts',
    pipelineCod: 'Pipeline COD',
    commune: 'Commune',
    customers: 'Customers',
    customer: 'Customer',
    city: 'City',
    submitted: 'Submitted',
    paidRevenue: 'Paid revenue',
    contribution: 'Contribution',
    margin: 'Margin',
    postedOrders: 'Posted orders',
    paidOrders: 'Paid orders',
    returnedOrders: 'Returned orders',
    costCoverage: 'Cost coverage',
    medianDelivery: 'Median delivery',
    units: 'Units',
    economicControls: 'Economic controls',
    period: 'Period',
    returnPercent: 'Return %',
    blankFieldsDefer: 'Blank fields defer independently to the automatic source.',
    orders: 'orders',
    terminal: 'terminal',
    eligible: 'eligible',
    resolved: 'resolved',
    postingCohorts: 'posting cohorts',
    terminalOrders: 'terminal orders',
    metaInsightsSynchronized: 'Meta insights synchronized.',
    googleSearchSynchronized: 'Google Search data synchronized.',
    syncFailed: 'Synchronization failed.',
    syncGoogle: 'Sync Google',
    played: 'Played',
    completed: 'Completed',
    outcomeWindow: 'outcome window',
    events: 'events',
    unavailable: 'unavailable',
    failed: 'failed',
    noEvent: 'No event',
    rawEventWindow: 'raw-event window',
    empty: '(empty)',
    zeroResultsShort: 'zero results',
    samples: 'samples',
    poor: 'poor',
    sessions: 'sessions',
    clicks: 'clicks',
    position: 'position',
    rankingPages: 'ranking pages',
    brand: 'brand',
    discovery: 'discovery',
    nearPageOne: 'Near page one',
    ctrGap: 'CTR gap',
    contentGap: 'Content gap',
    searchAppearance: 'Search appearance',
    urls: 'URLs',
    warnings: 'warnings',
    downloaded: 'downloaded',
    noUrlsInspected: 'No URLs inspected',
    pagesNeedReview: 'pages need review',
    noActionableIssue: 'No actionable issue in the current sample',
    openPublicPage: 'Open public page',
    searchProduct: 'Search product, SKU or category',
    above: 'Above',
    below: 'Below',
    insufficientProductOutcomes: 'Not enough resolved product outcomes for a reliable comparison.',
    noSku: 'No SKU',
    uncategorized: 'Uncategorized',
    metaReportedRegions: 'Meta-reported regions',
    aggregateMediaGeography: 'Aggregate media geography · not joined to customer wilayas',
    untracked: 'untracked',
    provider: 'provider',
    secondOrderConversion: 'Second-order conversion',
    exactMetaAssociations: 'Exact Meta associations',
    unknownCampaign: 'Unknown campaign',
    unknownAdSet: 'Unknown ad set',
    noExactAdAssociation: 'No exact ad-ID association in this range.',
    periodChange: 'Period change',
    assumptionsSaved: 'Assumptions saved.',
    operatingCostUpdated: 'Operating cost updated.',
    operatingCostAdded: 'Operating cost added.',
    operatingCostRemoved: 'Operating cost removed.',
    dailyOverrideSaved: 'Daily override saved.',
    dailyValuesReset: 'Daily values returned to automatic sources.',
    cpmEur: 'CPM EUR',
    analyticsRange: 'Analytics range',
    analyticsGrain: 'Analytics grain',
    startDate: 'Start date',
    endDate: 'End date',
    analyticsRequestFailed: 'Analytics request failed.',
    productViewSessions: 'Product-view sessions',
    cartSessions: 'Cart sessions',
    checkoutSessions: 'Checkout sessions',
    submittedOrderSessions: 'Submitted-order sessions',
    nextSevenDayModel: 'Next 7-day model',
  },
  modes: {
    projected: 'Projected',
    realized: 'Paid actual',
    cumulative: 'Cumulative',
    daily: 'Daily',
    campaign: 'Campaigns',
    adset: 'Ad sets',
    ad: 'Ads',
  },
  cashStages: {
    submitted: 'Submitted · unconfirmed',
    confirmed: 'Confirmed · unposted',
    inTransit: 'In transit',
    deliveredAwaitingCollection: 'Delivered · awaiting collection',
    collectedAwaitingPayout: 'Collected · awaiting payout',
    paymentReady: 'Payment ready',
    paid: 'Paid & archived',
  },
  fulfillmentPhases: {
    paid: 'Paid',
    return: 'Returned',
    cancelled: 'Cancelled',
    cash: 'Awaiting payment',
    delivery: 'Out for delivery',
    transit: 'In transit',
    ready: 'Ready to ship',
    exception: 'Needs review',
    untracked: 'Untracked',
  },
  expectedToPost: 'expected to post',
  returnCopy: {
    planning: 'Planning rate',
    mature: 'Mature observed',
    terminal: 'All terminal',
    useMature: 'Use mature rate',
    useTerminal: 'Use all-terminal rate',
    caveat:
      'Observed history is shown as evidence. It never changes the planning percentage unless you choose it.',
  },
  assumptions: {
    fx: 'EUR → DZD rate',
    defaultReturn: 'Default return rate',
    restFrom: 'Friday-rest active from',
    newCost: 'Add operating cost',
    costRetryRequired:
      'The response was interrupted. Save again to confirm this same cost before making other changes.',
    monthly: 'Monthly',
    once: 'One time',
    amount: 'Amount DZD',
    start: 'Start date',
    end: 'End date (optional)',
    newOverride: 'Edit daily override',
    gross: 'Gross profit DZD',
    confirmed: 'Posted or manual orders',
    returnRate: 'Return rate %',
    notes: 'Operator note',
    automatic: 'Automatic',
    default: 'Default',
    manual: 'Manual',
    missing: 'Missing',
  },
} as const;
