export const analyticsCopyFr = {
  loading: 'Mise à jour de la vue…',
  updated: 'Mis à jour',
  refresh: 'Actualiser',
  apply: 'Appliquer',
  cancel: 'Annuler',
  close: 'Fermer',
  save: 'Enregistrer',
  delete: 'Supprimer',
  reset: 'Revenir à l’automatique',
  export: 'Exporter CSV',
  syncMeta: 'Synchroniser la période Meta',
  syncing: 'Synchronisation…',
  inspect: 'Inspecter',
  compare: 'Comparer',
  previousPeriod: 'vs période précédente',
  noComparison: 'Aucune comparaison antérieure',
  noData: 'Aucune donnée fiable pour cette sélection.',
  partialPeriod: 'Période ouverte',
  exactRows: 'Valeurs exactes',
  sourceHealth: 'Sources de données',
  sourceNote: 'La couverture fait partie de la métrique, pas d’une note de bas de page.',
  ranges: {
    '7d': '7 jours',
    '14d': '14 jours',
    '30d': '30 jours',
    '90d': '90 jours',
    year: 'Année',
    all: 'Tout',
    custom: 'Personnalisé',
  },
  grains: { auto: 'Grain auto', day: 'Quotidien', week: 'Semaines vendredi', month: 'Mensuel' },
  metrics: {
    trueProfit: 'Profit réel',
    profitX: 'Profit ×',
    grossProfit: 'Profit brut',
    adjustedProfit: 'Profit ajusté',
    automaticPaidProfit: 'Profit des commandes payées',
    paidProfitCoverage: 'Couverture exacte des coûts payés',
    adCost: 'Coût Meta',
    postedOrders: 'Commandes expédiées',
    postedUnits: 'Unités expédiées',
    paidUnits: 'Unités payées',
    costPerPosted: 'Coût / expédiée',
    costPerDelivered: 'Coût / livrée',
    costPerPaid: 'Coût / payée',
    submittedOrders: 'Commandes saisies',
    paidOrders: 'Commandes payées',
    storefrontConversion: 'Conversion boutique',
    impressions: 'Impressions',
    outboundClicks: 'Clics sortants',
    landingPageViews: 'Vues de destination',
    activeShipments: 'Envois actifs',
    observedReturnRate: 'Retour mature',
    sessions: 'Sessions',
    engagementRate: 'Engagement',
    purchases: 'Commandes saisies',
    conversionRate: 'Conversion',
    errorRate: 'Taux d’erreur',
    returningJourneys: 'Parcours récurrents',
    productProfit: 'Référence de profit réglé',
    unitsSold: 'Unités vendues',
    customers: 'Clients',
    repeatRate: 'Taux de retour client',
    activeMonthlyBurn: 'Charge mensuelle',
    periodOperatingCost: 'Coûts de période',
    manualOverrideDays: 'Jours corrigés',
    projectedCoverage: 'Couverture des coûts',
    searchClicks: 'Clics Google',
    searchImpressions: 'Impressions de recherche',
    searchCtr: 'CTR de recherche',
    averagePosition: 'Position moyenne',
  },
  sections: {
    trajectory: 'Trajectoire de l’activité',
    signals: 'File opérateur',
    commerceFunnel: 'Maturité des commandes',
    cashPipeline: 'Pipeline de trésorerie',
    paidEconomics: 'Économie payée automatique',
    reconciliation: 'Référence de règlement',
    forecast: 'Projection',
    moneyPerformance: 'Performance financière',
    weeklyEconomics: 'Semaines débutant vendredi',
    economicsLedger: 'Registre économique',
    profitEfficiency: 'Efficacité du profit',
    creativeFatigue: 'Fatigue créative',
    creativeResponse: 'Réponse créative',
    paidFunnel: 'Entonnoir payant',
    hierarchy: 'Hiérarchie des campagnes',
    trackingHealth: 'Santé du tracking',
    deliveryPipeline: 'Pipeline de livraison',
    shipmentStates: 'États des envois',
    exceptionQueue: 'File des exceptions',
    cycleTime: 'Temps de cycle',
    attempts: 'Tentatives et résultat',
    cohorts: 'Cohortes de commandes expédiées',
    siteTrend: 'Tendance boutique',
    searchTrend: 'Demande de recherche',
    searchOpportunities: 'File d’opportunités',
    searchPages: 'Visibilité des pages',
    searchMix: 'Mix de découverte',
    indexHealth: 'Santé de l’index',
    siteFunnel: 'Entonnoir boutique',
    paths: 'Parcours récents',
    searches: 'Demande de recherche',
    landingPages: 'Landing pages',
    experience: 'Qualité de l’expérience',
    products: 'Intelligence produit',
    basketPairs: 'Produits achetés ensemble',
    geography: 'Zones et livraison',
    customerBase: 'Base clients',
    planningReturns: 'Taux de retour planifié',
    operatingCosts: 'Coûts d’exploitation',
    dailyOverrides: 'Corrections quotidiennes',
    formula: 'Formule canonique',
    automationEvidence: 'Automatisation face aux règlements',
  },
  sources: {
    orders: 'Commandes',
    ecotrack: 'EcoTrack',
    meta: 'Meta',
    storefront: 'Boutique',
    searchConsole: 'Recherche Google',
    settlements: 'Règlements',
    assumptions: 'Hypothèses manuelles',
  },
  sourceStates: {
    live: 'Direct',
    current: 'À jour',
    lagged: 'En retard',
    manual: 'Manuel',
    partial: 'Partiel',
    missing: 'Absent',
  },
  signalLabels: {
    belowBreakEven: 'Profit × sous le seuil de rentabilité',
    aboveBreakEven: 'Profit × au-dessus du seuil',
    returnAssumptionGap: 'Les retours observés diffèrent du plan',
    costCoverageGap: 'Snapshots de coût d’achat incomplets',
    fridayPending: 'Dépense du vendredi en attente de report',
    activePipeline: 'Des commandes sont encore en livraison',
  },
  warningLabels: {
    sourceMissing: 'Une source manque sur cette période',
    sourcePartial: 'Une source ne couvre qu’une partie de la période',
    projectedCostCoverage: 'Le profit projeté utilise une marge de secours de 30 %',
    pendingFridayRollforward: 'La dépense Meta du vendredi attend son report',
    pathRetentionPartial: 'Les parcours détaillés sont limités par la rétention des événements',
    searchDetailCoverage: 'Le détail requête/page est limité par la confidentialité Google',
  },
  columns: {
    date: 'Date',
    value: 'Valeur',
    status: 'État',
    orders: 'Commandes',
    spend: 'Dépense',
    profit: 'Profit',
    trueProfit: 'Profit réel',
    profitX: 'Profit ×',
    operatingCost: 'Coûts opérationnels',
    grossProfit: 'Profit brut',
    adjustedProfit: 'Profit ajusté',
    adCost: 'Coût pub',
    netProfit: 'Profit net',
    coverage: 'Couverture',
    name: 'Nom',
    campaign: 'Campagne',
    impressions: 'Impressions',
    ctr: 'CTR',
    outboundCtr: 'CTR sortant',
    cpm: 'CPM',
    landingViews: 'Vues destination',
    videoCompletion: 'Vidéo complète',
    watchTime: 'Visionnage moyen',
    ranking: 'Classement',
    confirmed: 'Confirmées',
    posted: 'Expédiées',
    paid: 'Payées',
    returned: 'Retournées',
    costPerPosted: 'Coût / expédiée',
    share: 'Part',
    stale: 'Bloquées >48 h',
    age: 'Âge médian',
    p50: 'Médiane',
    p75: 'P75',
    p90: 'P90',
    sample: 'Échantillon',
    sessions: 'Sessions',
    conversion: 'Conversion',
    views: 'Vues',
    carts: 'Paniers',
    revenue: 'Revenu',
    units: 'Unités',
    margin: 'Marge',
    category: 'Catégorie',
    brand: 'Marque',
    first: 'Premier',
    second: 'Second',
    repeat: 'Récurrence',
    source: 'Source',
    note: 'Note',
    query: 'Requête',
    page: 'Page',
    clicks: 'Clics',
    position: 'Position',
    potential: 'Clics potentiels',
    device: 'Appareil',
    country: 'Pays',
  },
  labels: {
    ecoTrackFee: 'Frais EcoTrack',
    paidCod: 'COD payé',
    estimatedFees: 'Frais estimés',
    netRecovered: 'Montant net récupéré',
    cod: 'COD',
    fees: 'Frais',
    providerCod: 'COD transporteur',
    profitMaturation: 'Maturation du profit',
    projectedTrueProfit: 'Profit réel projeté',
    deliveredTrueProfit: 'Profit réel livré',
    paidTrueProfit: 'Profit réel payé',
    postingWeek: 'Semaine de publication',
    posted: 'Publiées',
    delivered: 'Livrées',
    paid: 'Payées',
    projected: 'Projeté',
    paidProfit: 'Profit payé',
    variance: 'Écart',
    maturity: 'Maturité',
    open: 'Ouverte',
    upper: 'Haute',
    lower: 'Basse',
    beforeReturns: 'Avant retours',
    afterReturns: 'Après retours',
    playRate: 'Taux de lecture',
    completion: 'Complétion',
    averageWatch: 'Visionnage moyen',
    outboundCtr: 'CTR sortant',
    confirmationRate: 'Taux de confirmation',
    clickToPage: 'Clic → page',
    metaPurchases: 'Achats Meta',
    firstPartyOrders: 'Commandes first-party',
    exactAdIdCoverage: 'Couverture exacte des ID publicitaires',
    outcomeMaturity: 'Maturité des résultats',
    campaignMaturation: 'Maturation des campagnes',
    costPerPosted: 'Coût / publiée',
    costPerDelivered: 'Coût / livrée',
    costPerPaid: 'Coût / payée',
    metaSpend: 'Dépenses Meta',
    adCostDzd: 'Coût publicitaire DZD',
    outcomeWindowCost: 'Coût de la fenêtre de résultat',
    outcomeSpendCoverage: 'Couverture des dépenses attribuées',
    impressions: 'Impressions',
    outboundClicks: 'Clics sortants',
    uniqueOutbound: 'Clics sortants uniques',
    landingViews: 'Vues de destination',
    landingViewRate: 'Taux de vue de destination',
    videoPlays: 'Lectures vidéo',
    videoCompletion: 'Complétion vidéo',
    qualityRanking: 'Classement qualité',
    engagementRanking: 'Classement engagement',
    conversionRanking: 'Classement conversion',
    bricOrders: 'Commandes Bric',
    confirmed: 'Confirmées',
    returned: 'Retournées',
    projectedProfitX: 'Profit × projeté',
    paidProfitX: 'Profit × payé',
    profitCoverage: 'Couverture du profit',
    manualModelInput: 'Entrée manuelle du modèle',
    active: 'Actives',
    errors: 'Erreurs',
    productViewToCartSessions: 'Vue produit → panier',
    checkoutToSubmittedOrder: 'Paiement → commande soumise',
    from: 'De',
    to: 'Vers',
    aiAssistedShopping: 'Achats assistés par IA',
    opens: 'Ouvertures',
    messages: 'Messages',
    resultClicks: 'Clics sur résultat',
    influencedOrders: 'Commandes influencées',
    opportunity: 'Opportunité',
    searchLandingPagesDescription:
      'Pages de destination vues par Google. Sélectionnez une ligne pour examiner les requêtes qui créent sa visibilité.',
    queries: 'Requêtes',
    devices: 'Appareils',
    countries: 'Pays',
    sitemap: 'Plan du site',
    inspectedSample: 'Échantillon inspecté',
    searchOpportunityEvidence: 'Preuves de l’opportunité de recherche',
    currentCtr: 'CTR actuel',
    comparableCtr: 'CTR comparable',
    googleLandingPageEvidence: 'Preuves Google de la page de destination',
    productViews: 'Vues produit',
    terminalPaid: 'Payées terminales',
    paidReturned: 'Payées / retournées',
    stillActive: 'Encore actives',
    scatterViews: 'Vues →',
    scatterPaidOutcome: 'Résultat payé ↑',
    bubbleResolvedOrders: 'Bulle · commandes résolues',
    terminalPaidRate: 'Taux payé terminal',
    postedUnits: 'Unités publiées',
    projectedContribution: 'Contribution projetée',
    delivery: 'Livraison',
    wilaya: 'Wilaya',
    attempts: 'Tentatives',
    pipelineCod: 'COD en cours',
    commune: 'Commune',
    customers: 'Clients',
    customer: 'Client',
    city: 'Ville',
    submitted: 'Soumises',
    paidRevenue: 'Chiffre payé',
    contribution: 'Contribution',
    margin: 'Marge',
    postedOrders: 'Commandes publiées',
    paidOrders: 'Commandes payées',
    returnedOrders: 'Commandes retournées',
    costCoverage: 'Couverture des coûts',
    medianDelivery: 'Livraison médiane',
    units: 'Unités',
    economicControls: 'Paramètres économiques',
    period: 'Période',
    returnPercent: 'Retour %',
    blankFieldsDefer: 'Les champs vides utilisent séparément la source automatique.',
    orders: 'commandes',
    terminal: 'terminaux',
    eligible: 'éligibles',
    resolved: 'résolus',
    postingCohorts: 'cohortes de publication',
    terminalOrders: 'commandes terminales',
    metaInsightsSynchronized: 'Données Meta synchronisées.',
    googleSearchSynchronized: 'Données Google Search synchronisées.',
    syncFailed: 'Échec de la synchronisation.',
    syncGoogle: 'Synchroniser Google',
    played: 'Lectures',
    completed: 'Terminées',
    outcomeWindow: 'fenêtre de résultat',
    events: 'événements',
    unavailable: 'indisponible',
    failed: 'en échec',
    noEvent: 'Aucun événement',
    rawEventWindow: 'fenêtre des événements bruts',
    empty: '(vide)',
    zeroResultsShort: 'sans résultat',
    samples: 'échantillons',
    poor: 'médiocres',
    sessions: 'sessions',
    clicks: 'clics',
    position: 'position',
    rankingPages: 'pages classées',
    brand: 'marque',
    discovery: 'découverte',
    nearPageOne: 'Près de la première page',
    ctrGap: 'Écart de CTR',
    contentGap: 'Contenu manquant',
    searchAppearance: 'Apparence dans la recherche',
    urls: 'URL',
    warnings: 'avertissements',
    downloaded: 'téléchargé',
    noUrlsInspected: 'Aucune URL inspectée',
    pagesNeedReview: 'pages à examiner',
    noActionableIssue: 'Aucun problème exploitable dans l’échantillon actuel',
    openPublicPage: 'Ouvrir la page publique',
    searchProduct: 'Rechercher un produit, SKU ou une catégorie',
    above: 'Au-dessus',
    below: 'En dessous',
    insufficientProductOutcomes:
      'Pas assez de résultats produit résolus pour une comparaison fiable.',
    noSku: 'Sans SKU',
    uncategorized: 'Sans catégorie',
    metaReportedRegions: 'Régions déclarées par Meta',
    aggregateMediaGeography: 'Géographie média agrégée · non reliée aux wilayas clients',
    untracked: 'non suivies',
    provider: 'transporteur',
    secondOrderConversion: 'Conversion vers la deuxième commande',
    exactMetaAssociations: 'Associations Meta exactes',
    unknownCampaign: 'Campagne inconnue',
    unknownAdSet: 'Ensemble publicitaire inconnu',
    noExactAdAssociation: 'Aucune association exacte par ID publicitaire sur cette période.',
    periodChange: 'Évolution de la période',
    assumptionsSaved: 'Hypothèses enregistrées.',
    operatingCostUpdated: 'Coût d’exploitation mis à jour.',
    operatingCostAdded: 'Coût d’exploitation ajouté.',
    operatingCostRemoved: 'Coût d’exploitation supprimé.',
    dailyOverrideSaved: 'Ajustement quotidien enregistré.',
    dailyValuesReset: 'Valeurs quotidiennes revenues aux sources automatiques.',
    cpmEur: 'CPM EUR',
    analyticsRange: 'Période analytique',
    analyticsGrain: 'Granularité analytique',
    startDate: 'Date de début',
    endDate: 'Date de fin',
    analyticsRequestFailed: 'Échec de la requête analytique.',
    productViewSessions: 'Sessions avec vue produit',
    cartSessions: 'Sessions avec panier',
    checkoutSessions: 'Sessions de paiement',
    submittedOrderSessions: 'Sessions avec commande soumise',
    nextSevenDayModel: 'Modèle des 7 prochains jours',
  },
  modes: {
    projected: 'Projeté',
    realized: 'Payé réel',
    cumulative: 'Cumulé',
    daily: 'Quotidien',
    campaign: 'Campagnes',
    adset: 'Ensembles',
    ad: 'Publicités',
  },
  cashStages: {
    submitted: 'Soumises · non confirmées',
    confirmed: 'Confirmées · non publiées',
    inTransit: 'En transit',
    deliveredAwaitingCollection: 'Livré · collecte en attente',
    collectedAwaitingPayout: 'Encaissé · paiement en attente',
    paymentReady: 'Paiement prêt',
    paid: 'Payé et archivé',
  },
  fulfillmentPhases: {
    paid: 'Payées',
    return: 'Retournées',
    cancelled: 'Annulées',
    cash: 'Paiement en attente',
    delivery: 'En livraison',
    transit: 'En transit',
    ready: 'Prêtes à expédier',
    exception: 'À examiner',
    untracked: 'Non suivies',
  },
  expectedToPost: 'devraient être publiées',
  returnCopy: {
    planning: 'Taux de planification',
    mature: 'Observé mature',
    terminal: 'Tous les terminaux',
    useMature: 'Utiliser le taux mature',
    useTerminal: 'Utiliser les terminaux',
    caveat:
      'L’historique observé est une preuve. Il ne change jamais le taux de planification sans votre choix.',
  },
  assumptions: {
    fx: 'Taux EUR → DZD',
    defaultReturn: 'Taux de retour par défaut',
    restFrom: 'Repos vendredi actif depuis',
    newCost: 'Ajouter un coût',
    monthly: 'Mensuel',
    once: 'Ponctuel',
    amount: 'Montant DZD',
    start: 'Date de début',
    end: 'Date de fin (optionnel)',
    newOverride: 'Modifier la journée',
    gross: 'Profit brut DZD',
    confirmed: 'Commandes confirmées',
    returnRate: 'Taux de retour %',
    notes: 'Note opérateur',
    automatic: 'Automatique',
    default: 'Par défaut',
    manual: 'Manuel',
    missing: 'Absent',
  },
} as const;
