const aiStatsCopy = {
  en: {
    operationsTitle: 'AI operations',
    shoppingTitle: 'Shopping assistant',
    updated: 'Updated',
    refresh: 'Refresh',
    apply: 'Apply',
    noData: 'No data for this selection.',
    requestFailed: 'AI analytics could not be loaded.',
    ranges: {
      '7d': '7 days',
      '14d': '14 days',
      '30d': '30 days',
      '90d': '90 days',
      year: 'Year',
      all: 'All',
      custom: 'Custom',
    },
    grains: { auto: 'Auto grain', day: 'Daily', week: 'Weekly', month: 'Monthly' },
    metrics: {
      interactiveRequests: 'Interactive requests',
      responseCompletion: 'Response completion',
      toolCompletion: 'Tool completion',
      p95Latency: 'P95 latency',
      helpfulRatings: 'Helpful ratings',
      costPerCompletion: 'Cost / completion',
      engagedJourneys: 'Questions',
      resultClickRate: 'Result click rate',
      recommendedOrders: 'Recommended-product orders',
      confirmedAssisted: 'Confirmed assisted orders',
      paidAssisted: 'Paid assisted orders',
      paidContribution: 'Paid contribution',
    },
    sections: {
      outcomeTrend: 'Interactive outcomes',
      workflows: 'Workflows',
      tools: 'Tool reliability',
      releases: 'Releases',
      changes: 'Change outcomes',
      exceptions: 'Recent exceptions',
      journey: 'Assistant journey',
      demandTrend: 'Assistant demand',
      intents: 'Shopper intents',
      reliability: 'Reliability',
    },
    columns: {
      workflow: 'Workflow',
      mode: 'Mode',
      runs: 'Runs',
      completion: 'Completion',
      failures: 'Failed',
      latency: 'P95',
      tokens: 'Tokens',
      cost: 'Cost',
      tool: 'Tool',
      calls: 'Calls',
      prompt: 'Prompt',
      model: 'Model',
      type: 'Type',
      status: 'Status',
      count: 'Count',
      date: 'Date',
      intent: 'Intent',
      questions: 'Questions',
      clicks: 'Clicks',
    },
    workload: {
      interactive: 'Interactive',
      deterministic: 'Deterministic',
      batch: 'Batch',
    },
    journey: {
      opened: 'Opened',
      messaged: 'Question sent',
      resultClicked: 'Result clicked',
      engagedOrder: 'Engaged order',
      recommendedOrder: 'Recommended product ordered',
      confirmed: 'Confirmed',
      paid: 'Paid',
    },
    reliability: {
      activeJourneys: 'Active journeys',
      completedRuns: 'Completed runs',
      failedRuns: 'Failed runs',
      p95Latency: 'P95 latency',
      ratings: 'Ratings',
      estimatedCost: 'Estimated cost',
      noRatings: 'No ratings',
    },
    chart: {
      completed: 'Completed',
      failed: 'Failed',
      cancelled: 'Cancelled',
      questions: 'Questions',
      resultClicks: 'Result clicks',
    },
  },
  fr: {
    operationsTitle: 'Opérations IA',
    shoppingTitle: 'Assistant d’achat',
    updated: 'Mis à jour',
    refresh: 'Actualiser',
    apply: 'Appliquer',
    noData: 'Aucune donnée pour cette sélection.',
    requestFailed: 'Les statistiques IA n’ont pas pu être chargées.',
    ranges: {
      '7d': '7 jours',
      '14d': '14 jours',
      '30d': '30 jours',
      '90d': '90 jours',
      year: 'Année',
      all: 'Tout',
      custom: 'Personnalisé',
    },
    grains: { auto: 'Grain auto', day: 'Quotidien', week: 'Hebdomadaire', month: 'Mensuel' },
    metrics: {
      interactiveRequests: 'Demandes interactives',
      responseCompletion: 'Réponses terminées',
      toolCompletion: 'Outils terminés',
      p95Latency: 'Latence P95',
      helpfulRatings: 'Avis utiles',
      costPerCompletion: 'Coût / résultat',
      engagedJourneys: 'Questions',
      resultClickRate: 'Taux de clic résultat',
      recommendedOrders: 'Commandes recommandées',
      confirmedAssisted: 'Commandes assistées confirmées',
      paidAssisted: 'Commandes assistées payées',
      paidContribution: 'Contribution payée',
    },
    sections: {
      outcomeTrend: 'Résultats interactifs',
      workflows: 'Flux de travail',
      tools: 'Fiabilité des outils',
      releases: 'Versions',
      changes: 'Résultats des changements',
      exceptions: 'Exceptions récentes',
      journey: 'Parcours assistant',
      demandTrend: 'Demande assistant',
      intents: 'Intentions clients',
      reliability: 'Fiabilité',
    },
    columns: {
      workflow: 'Flux',
      mode: 'Mode',
      runs: 'Exécutions',
      completion: 'Réussite',
      failures: 'Échecs',
      latency: 'P95',
      tokens: 'Jetons',
      cost: 'Coût',
      tool: 'Outil',
      calls: 'Appels',
      prompt: 'Prompt',
      model: 'Modèle',
      type: 'Type',
      status: 'Statut',
      count: 'Nombre',
      date: 'Date',
      intent: 'Intention',
      questions: 'Questions',
      clicks: 'Clics',
    },
    workload: { interactive: 'Interactif', deterministic: 'Déterministe', batch: 'Lot' },
    journey: {
      opened: 'Ouvert',
      messaged: 'Question envoyée',
      resultClicked: 'Résultat cliqué',
      engagedOrder: 'Commande engagée',
      recommendedOrder: 'Produit recommandé commandé',
      confirmed: 'Confirmée',
      paid: 'Payée',
    },
    reliability: {
      activeJourneys: 'Parcours actifs',
      completedRuns: 'Exécutions terminées',
      failedRuns: 'Échecs',
      p95Latency: 'Latence P95',
      ratings: 'Avis',
      estimatedCost: 'Coût estimé',
      noRatings: 'Aucun avis',
    },
    chart: {
      completed: 'Terminées',
      failed: 'Échecs',
      cancelled: 'Annulées',
      questions: 'Questions',
      resultClicks: 'Clics résultat',
    },
  },
  ar: {
    operationsTitle: 'عمليات الذكاء الاصطناعي',
    shoppingTitle: 'مساعد التسوق',
    updated: 'آخر تحديث',
    refresh: 'تحديث',
    apply: 'تطبيق',
    noData: 'لا توجد بيانات لهذا التحديد.',
    requestFailed: 'تعذر تحميل تحليلات الذكاء الاصطناعي.',
    ranges: {
      '7d': '7 أيام',
      '14d': '14 يومًا',
      '30d': '30 يومًا',
      '90d': '90 يومًا',
      year: 'السنة',
      all: 'الكل',
      custom: 'مخصص',
    },
    grains: { auto: 'تجميع تلقائي', day: 'يومي', week: 'أسبوعي', month: 'شهري' },
    metrics: {
      interactiveRequests: 'الطلبات التفاعلية',
      responseCompletion: 'اكتمال الردود',
      toolCompletion: 'اكتمال الأدوات',
      p95Latency: 'زمن P95',
      helpfulRatings: 'التقييمات المفيدة',
      costPerCompletion: 'التكلفة / اكتمال',
      engagedJourneys: 'الأسئلة',
      resultClickRate: 'معدل نقر النتائج',
      recommendedOrders: 'طلبات المنتجات المقترحة',
      confirmedAssisted: 'الطلبات المساعدة المؤكدة',
      paidAssisted: 'الطلبات المساعدة المدفوعة',
      paidContribution: 'المساهمة المدفوعة',
    },
    sections: {
      outcomeTrend: 'نتائج التفاعل',
      workflows: 'سير العمل',
      tools: 'موثوقية الأدوات',
      releases: 'الإصدارات',
      changes: 'نتائج التغييرات',
      exceptions: 'الاستثناءات الأخيرة',
      journey: 'مسار المساعد',
      demandTrend: 'طلب المساعد',
      intents: 'نوايا المتسوقين',
      reliability: 'الموثوقية',
    },
    columns: {
      workflow: 'سير العمل',
      mode: 'الوضع',
      runs: 'التشغيلات',
      completion: 'الاكتمال',
      failures: 'الفشل',
      latency: 'P95',
      tokens: 'الرموز',
      cost: 'التكلفة',
      tool: 'الأداة',
      calls: 'الاستدعاءات',
      prompt: 'الموجه',
      model: 'النموذج',
      type: 'النوع',
      status: 'الحالة',
      count: 'العدد',
      date: 'التاريخ',
      intent: 'النية',
      questions: 'الأسئلة',
      clicks: 'النقرات',
    },
    workload: { interactive: 'تفاعلي', deterministic: 'حتمي', batch: 'دفعي' },
    journey: {
      opened: 'فتح المساعد',
      messaged: 'إرسال سؤال',
      resultClicked: 'نقر نتيجة',
      engagedOrder: 'طلب متفاعل',
      recommendedOrder: 'طلب منتج مقترح',
      confirmed: 'مؤكد',
      paid: 'مدفوع',
    },
    reliability: {
      activeJourneys: 'المسارات النشطة',
      completedRuns: 'التشغيلات المكتملة',
      failedRuns: 'التشغيلات الفاشلة',
      p95Latency: 'زمن P95',
      ratings: 'التقييمات',
      estimatedCost: 'التكلفة المقدرة',
      noRatings: 'لا توجد تقييمات',
    },
    chart: {
      completed: 'مكتمل',
      failed: 'فشل',
      cancelled: 'ملغى',
      questions: 'الأسئلة',
      resultClicks: 'نقرات النتائج',
    },
  },
} as const;

export type AiStatsCopy = (typeof aiStatsCopy)['en'];

export function getAiStatsCopy(locale: string): AiStatsCopy {
  return (aiStatsCopy[locale as keyof typeof aiStatsCopy] ?? aiStatsCopy.en) as AiStatsCopy;
}
