export const analytics2Copy = {
  en: {
    loading: 'Updating this view…',
    updated: 'Updated',
    refresh: 'Refresh',
    apply: 'Apply',
    cancel: 'Cancel',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    reset: 'Reset to automatic',
    export: 'Export CSV',
    syncMeta: 'Sync Meta range',
    syncing: 'Synchronizing…',
    inspect: 'Inspect',
    compare: 'Compare',
    previousPeriod: 'vs previous period',
    noComparison: 'No comparable period',
    noData: 'No trustworthy data for this selection.',
    partialPeriod: 'Open period',
    exactRows: 'Exact values',
    sourceHealth: 'Data sources',
    sourceNote: 'Coverage is part of the metric, not a footnote.',
    ranges: {
      '7d': '7 days',
      '14d': '14 days',
      '30d': '30 days',
      '90d': '90 days',
      year: 'Year',
      all: 'All',
      custom: 'Custom',
    },
    grains: { auto: 'Auto grain', day: 'Daily', week: 'Friday weeks', month: 'Monthly' },
    metrics: {
      trueProfit: 'True profit',
      profitX: 'Profit ×',
      adjustedProfit: 'Adjusted profit',
      automaticPaidProfit: 'Paid-order profit',
      paidProfitCoverage: 'Exact paid-cost coverage',
      adCost: 'Meta cost',
      postedOrders: 'Posted orders',
      postedUnits: 'Posted units',
      paidUnits: 'Paid units',
      costPerPosted: 'Cost / posted',
      costPerDelivered: 'Cost / delivered',
      costPerPaid: 'Cost / paid',
      submittedOrders: 'Submitted orders',
      paidOrders: 'Paid orders',
      storefrontConversion: 'Store conversion',
      impressions: 'Impressions',
      outboundClicks: 'Outbound clicks',
      landingPageViews: 'Landing views',
      activeShipments: 'Active shipments',
      observedReturnRate: 'Mature return rate',
      sessions: 'Sessions',
      engagementRate: 'Engagement',
      purchases: 'Orders placed',
      conversionRate: 'Conversion',
      errorRate: 'Error rate',
      returningJourneys: 'Returning journeys',
      productProfit: 'Settlement profit reference',
      unitsSold: 'Units sold',
      customers: 'Customers',
      repeatRate: 'Repeat rate',
      activeMonthlyBurn: 'Monthly burn',
      periodOperatingCost: 'Period operating cost',
      manualOverrideDays: 'Override days',
      projectedCoverage: 'Cost coverage',
      searchClicks: 'Google clicks',
      searchImpressions: 'Search impressions',
      searchCtr: 'Search CTR',
      averagePosition: 'Average position',
    },
    sections: {
      trajectory: 'Profit',
      signals: 'Signals',
      commerceFunnel: 'Order maturity',
      cashPipeline: 'Cash pipeline',
      paidEconomics: 'Paid economics',
      reconciliation: 'Settlement reference',
      forecast: 'Forward view',
      moneyPerformance: 'Financial performance',
      weeklyEconomics: 'Friday-start weeks',
      economicsLedger: 'Economics ledger',
      profitEfficiency: 'Profit efficiency',
      creativeFatigue: 'Creative fatigue',
      creativeResponse: 'Creative response',
      paidFunnel: 'Paid funnel',
      hierarchy: 'Campaign hierarchy',
      trackingHealth: 'Tracking health',
      deliveryPipeline: 'Delivery pipeline',
      shipmentStates: 'Shipment states',
      exceptionQueue: 'Exception queue',
      cycleTime: 'Cycle time',
      attempts: 'Attempts versus outcome',
      cohorts: 'Posted-order cohorts',
      siteTrend: 'Storefront trend',
      searchTrend: 'Search demand',
      searchOpportunities: 'Opportunity queue',
      searchPages: 'Landing-page visibility',
      searchMix: 'Discovery mix',
      indexHealth: 'Index health',
      siteFunnel: 'Storefront funnel',
      paths: 'Recent paths',
      searches: 'Search demand',
      landingPages: 'Landing pages',
      experience: 'Experience quality',
      products: 'Product intelligence',
      basketPairs: 'Products bought together',
      geography: 'Geography and delivery',
      customerBase: 'Customer base',
      planningReturns: 'Planning return rate',
      operatingCosts: 'Operating costs',
      dailyOverrides: 'Daily source overrides',
      formula: 'Canonical formula',
      automationEvidence: 'Automation versus settlement evidence',
    },
    sources: {
      orders: 'Orders',
      ecotrack: 'EcoTrack',
      meta: 'Meta',
      storefront: 'Storefront',
      searchConsole: 'Google Search',
      settlements: 'Settlements',
      assumptions: 'Manual assumptions',
    },
    sourceStates: {
      live: 'Live',
      current: 'Current',
      lagged: 'Lagged',
      manual: 'Manual',
      partial: 'Partial',
      missing: 'Missing',
    },
    signalLabels: {
      belowBreakEven: 'Profit × is below break-even',
      aboveBreakEven: 'Profit × is above break-even',
      returnAssumptionGap: 'Observed returns differ from planning',
      costCoverageGap: 'Purchase-cost snapshots are incomplete',
      fridayPending: 'Friday spend awaits roll-forward',
      activePipeline: 'Orders are still moving through delivery',
    },
    warningLabels: {
      sourceMissing: 'A source is missing for this range',
      sourcePartial: 'A source only covers part of this range',
      projectedCostCoverage: 'Projected profit uses a 30% fallback margin for missing costs',
      pendingFridayRollforward: 'Friday Meta spend is pending roll-forward',
      pathRetentionPartial: 'Path detail is limited by raw-event retention',
      searchDetailCoverage: 'Query and page detail is privacy-limited by Google',
    },
    columns: {
      date: 'Date',
      value: 'Value',
      status: 'Status',
      orders: 'Orders',
      spend: 'Spend',
      profit: 'Profit',
      trueProfit: 'True profit',
      profitX: 'Profit ×',
      operatingCost: 'Operating costs',
      grossProfit: 'Gross profit',
      adjustedProfit: 'Adjusted profit',
      adCost: 'Ad cost',
      netProfit: 'Net profit',
      coverage: 'Coverage',
      name: 'Name',
      campaign: 'Campaign',
      impressions: 'Impressions',
      ctr: 'CTR',
      outboundCtr: 'Outbound CTR',
      cpm: 'CPM',
      landingViews: 'Landing views',
      videoCompletion: 'Video complete',
      watchTime: 'Avg watch',
      ranking: 'Ranking',
      confirmed: 'Confirmed',
      posted: 'Posted',
      paid: 'Paid',
      returned: 'Returned',
      costPerPosted: 'Cost / posted',
      share: 'Share',
      stale: 'Stale >48h',
      age: 'Median age',
      p50: 'Median',
      p75: 'P75',
      p90: 'P90',
      sample: 'Sample',
      sessions: 'Sessions',
      conversion: 'Conversion',
      views: 'Views',
      carts: 'Carts',
      revenue: 'Revenue',
      units: 'Units',
      margin: 'Margin',
      category: 'Category',
      brand: 'Brand',
      first: 'First',
      second: 'Second',
      repeat: 'Repeat',
      source: 'Source',
      note: 'Note',
      query: 'Query',
      page: 'Page',
      clicks: 'Clicks',
      position: 'Position',
      potential: 'Potential clicks',
      device: 'Device',
      country: 'Country',
    },
    modes: {
      projected: 'Projected',
      realized: 'Paid actual',
      cumulative: 'Cumulative',
      daily: 'Daily',
      campaign: 'Campaigns',
      adset: 'Ad sets',
      ad: 'Ads',
    },
    cashStages: {
      submitted: 'Submitted · unconfirmed',
      confirmed: 'Confirmed · unposted',
      inTransit: 'In transit',
      deliveredAwaitingCollection: 'Delivered · awaiting collection',
      collectedAwaitingPayout: 'Collected · awaiting payout',
      paymentReady: 'Payment ready',
      paid: 'Paid & archived',
    },
    expectedToPost: 'expected to post',
    returnCopy: {
      planning: 'Planning rate',
      mature: 'Mature observed',
      terminal: 'All terminal',
      useMature: 'Use mature rate',
      useTerminal: 'Use all-terminal rate',
      caveat:
        'Observed history is shown as evidence. It never changes the planning percentage unless you choose it.',
    },
    assumptions: {
      fx: 'EUR → DZD rate',
      defaultReturn: 'Default return rate',
      restFrom: 'Friday-rest active from',
      newCost: 'Add operating cost',
      monthly: 'Monthly',
      once: 'One time',
      amount: 'Amount DZD',
      start: 'Start date',
      end: 'End date (optional)',
      newOverride: 'Edit daily override',
      gross: 'Gross profit DZD',
      confirmed: 'Confirmed orders',
      returnRate: 'Return rate %',
      notes: 'Operator note',
      automatic: 'Automatic',
      manual: 'Manual',
      missing: 'Missing',
    },
  },
  fr: {
    loading: 'Mise à jour de la vue…',
    updated: 'Mis à jour',
    refresh: 'Actualiser',
    apply: 'Appliquer',
    cancel: 'Annuler',
    close: 'Fermer',
    save: 'Enregistrer',
    delete: 'Supprimer',
    reset: 'Revenir à l’automatique',
    export: 'Exporter CSV',
    syncMeta: 'Synchroniser la période Meta',
    syncing: 'Synchronisation…',
    inspect: 'Inspecter',
    compare: 'Comparer',
    previousPeriod: 'vs période précédente',
    noComparison: 'Aucune comparaison antérieure',
    noData: 'Aucune donnée fiable pour cette sélection.',
    partialPeriod: 'Période ouverte',
    exactRows: 'Valeurs exactes',
    sourceHealth: 'Sources de données',
    sourceNote: 'La couverture fait partie de la métrique, pas d’une note de bas de page.',
    ranges: {
      '7d': '7 jours',
      '14d': '14 jours',
      '30d': '30 jours',
      '90d': '90 jours',
      year: 'Année',
      all: 'Tout',
      custom: 'Personnalisé',
    },
    grains: { auto: 'Grain auto', day: 'Quotidien', week: 'Semaines vendredi', month: 'Mensuel' },
    metrics: {
      trueProfit: 'Profit réel',
      profitX: 'Profit ×',
      adjustedProfit: 'Profit ajusté',
      automaticPaidProfit: 'Profit des commandes payées',
      paidProfitCoverage: 'Couverture exacte des coûts payés',
      adCost: 'Coût Meta',
      postedOrders: 'Commandes expédiées',
      postedUnits: 'Unités expédiées',
      paidUnits: 'Unités payées',
      costPerPosted: 'Coût / expédiée',
      costPerDelivered: 'Coût / livrée',
      costPerPaid: 'Coût / payée',
      submittedOrders: 'Commandes saisies',
      paidOrders: 'Commandes payées',
      storefrontConversion: 'Conversion boutique',
      impressions: 'Impressions',
      outboundClicks: 'Clics sortants',
      landingPageViews: 'Vues de destination',
      activeShipments: 'Envois actifs',
      observedReturnRate: 'Retour mature',
      sessions: 'Sessions',
      engagementRate: 'Engagement',
      purchases: 'Commandes saisies',
      conversionRate: 'Conversion',
      errorRate: 'Taux d’erreur',
      returningJourneys: 'Parcours récurrents',
      productProfit: 'Référence de profit réglé',
      unitsSold: 'Unités vendues',
      customers: 'Clients',
      repeatRate: 'Taux de retour client',
      activeMonthlyBurn: 'Charge mensuelle',
      periodOperatingCost: 'Coûts de période',
      manualOverrideDays: 'Jours corrigés',
      projectedCoverage: 'Couverture des coûts',
      searchClicks: 'Clics Google',
      searchImpressions: 'Impressions de recherche',
      searchCtr: 'CTR de recherche',
      averagePosition: 'Position moyenne',
    },
    sections: {
      trajectory: 'Trajectoire de l’activité',
      signals: 'File opérateur',
      commerceFunnel: 'Maturité des commandes',
      cashPipeline: 'Pipeline de trésorerie',
      paidEconomics: 'Économie payée automatique',
      reconciliation: 'Référence de règlement',
      forecast: 'Projection',
      moneyPerformance: 'Performance financière',
      weeklyEconomics: 'Semaines débutant vendredi',
      economicsLedger: 'Registre économique',
      profitEfficiency: 'Efficacité du profit',
      creativeFatigue: 'Fatigue créative',
      creativeResponse: 'Réponse créative',
      paidFunnel: 'Entonnoir payant',
      hierarchy: 'Hiérarchie des campagnes',
      trackingHealth: 'Santé du tracking',
      deliveryPipeline: 'Pipeline de livraison',
      shipmentStates: 'États des envois',
      exceptionQueue: 'File des exceptions',
      cycleTime: 'Temps de cycle',
      attempts: 'Tentatives et résultat',
      cohorts: 'Cohortes de commandes expédiées',
      siteTrend: 'Tendance boutique',
      searchTrend: 'Demande de recherche',
      searchOpportunities: 'File d’opportunités',
      searchPages: 'Visibilité des pages',
      searchMix: 'Mix de découverte',
      indexHealth: 'Santé de l’index',
      siteFunnel: 'Entonnoir boutique',
      paths: 'Parcours récents',
      searches: 'Demande de recherche',
      landingPages: 'Landing pages',
      experience: 'Qualité de l’expérience',
      products: 'Intelligence produit',
      basketPairs: 'Produits achetés ensemble',
      geography: 'Zones et livraison',
      customerBase: 'Base clients',
      planningReturns: 'Taux de retour planifié',
      operatingCosts: 'Coûts d’exploitation',
      dailyOverrides: 'Corrections quotidiennes',
      formula: 'Formule canonique',
      automationEvidence: 'Automatisation face aux règlements',
    },
    sources: {
      orders: 'Commandes',
      ecotrack: 'EcoTrack',
      meta: 'Meta',
      storefront: 'Boutique',
      searchConsole: 'Recherche Google',
      settlements: 'Règlements',
      assumptions: 'Hypothèses manuelles',
    },
    sourceStates: {
      live: 'Direct',
      current: 'À jour',
      lagged: 'En retard',
      manual: 'Manuel',
      partial: 'Partiel',
      missing: 'Absent',
    },
    signalLabels: {
      belowBreakEven: 'Profit × sous le seuil de rentabilité',
      aboveBreakEven: 'Profit × au-dessus du seuil',
      returnAssumptionGap: 'Les retours observés diffèrent du plan',
      costCoverageGap: 'Snapshots de coût d’achat incomplets',
      fridayPending: 'Dépense du vendredi en attente de report',
      activePipeline: 'Des commandes sont encore en livraison',
    },
    warningLabels: {
      sourceMissing: 'Une source manque sur cette période',
      sourcePartial: 'Une source ne couvre qu’une partie de la période',
      projectedCostCoverage: 'Le profit projeté utilise une marge de secours de 30 %',
      pendingFridayRollforward: 'La dépense Meta du vendredi attend son report',
      pathRetentionPartial: 'Les parcours détaillés sont limités par la rétention des événements',
      searchDetailCoverage: 'Le détail requête/page est limité par la confidentialité Google',
    },
    columns: {
      date: 'Date',
      value: 'Valeur',
      status: 'État',
      orders: 'Commandes',
      spend: 'Dépense',
      profit: 'Profit',
      trueProfit: 'Profit réel',
      profitX: 'Profit ×',
      operatingCost: 'Coûts opérationnels',
      grossProfit: 'Profit brut',
      adjustedProfit: 'Profit ajusté',
      adCost: 'Coût pub',
      netProfit: 'Profit net',
      coverage: 'Couverture',
      name: 'Nom',
      campaign: 'Campagne',
      impressions: 'Impressions',
      ctr: 'CTR',
      outboundCtr: 'CTR sortant',
      cpm: 'CPM',
      landingViews: 'Vues destination',
      videoCompletion: 'Vidéo complète',
      watchTime: 'Visionnage moyen',
      ranking: 'Classement',
      confirmed: 'Confirmées',
      posted: 'Expédiées',
      paid: 'Payées',
      returned: 'Retournées',
      costPerPosted: 'Coût / expédiée',
      share: 'Part',
      stale: 'Bloquées >48 h',
      age: 'Âge médian',
      p50: 'Médiane',
      p75: 'P75',
      p90: 'P90',
      sample: 'Échantillon',
      sessions: 'Sessions',
      conversion: 'Conversion',
      views: 'Vues',
      carts: 'Paniers',
      revenue: 'Revenu',
      units: 'Unités',
      margin: 'Marge',
      category: 'Catégorie',
      brand: 'Marque',
      first: 'Premier',
      second: 'Second',
      repeat: 'Récurrence',
      source: 'Source',
      note: 'Note',
      query: 'Requête',
      page: 'Page',
      clicks: 'Clics',
      position: 'Position',
      potential: 'Clics potentiels',
      device: 'Appareil',
      country: 'Pays',
    },
    modes: {
      projected: 'Projeté',
      realized: 'Payé réel',
      cumulative: 'Cumulé',
      daily: 'Quotidien',
      campaign: 'Campagnes',
      adset: 'Ensembles',
      ad: 'Publicités',
    },
    cashStages: {
      submitted: 'Soumises · non confirmées',
      confirmed: 'Confirmées · non publiées',
      inTransit: 'En transit',
      deliveredAwaitingCollection: 'Livré · collecte en attente',
      collectedAwaitingPayout: 'Encaissé · paiement en attente',
      paymentReady: 'Paiement prêt',
      paid: 'Payé et archivé',
    },
    expectedToPost: 'devraient être publiées',
    returnCopy: {
      planning: 'Taux de planification',
      mature: 'Observé mature',
      terminal: 'Tous les terminaux',
      useMature: 'Utiliser le taux mature',
      useTerminal: 'Utiliser les terminaux',
      caveat:
        'L’historique observé est une preuve. Il ne change jamais le taux de planification sans votre choix.',
    },
    assumptions: {
      fx: 'Taux EUR → DZD',
      defaultReturn: 'Taux de retour par défaut',
      restFrom: 'Repos vendredi actif depuis',
      newCost: 'Ajouter un coût',
      monthly: 'Mensuel',
      once: 'Ponctuel',
      amount: 'Montant DZD',
      start: 'Date de début',
      end: 'Date de fin (optionnel)',
      newOverride: 'Modifier la journée',
      gross: 'Profit brut DZD',
      confirmed: 'Commandes confirmées',
      returnRate: 'Taux de retour %',
      notes: 'Note opérateur',
      automatic: 'Automatique',
      manual: 'Manuel',
      missing: 'Absent',
    },
  },
  ar: {
    loading: 'جارٍ تحديث العرض…',
    updated: 'آخر تحديث',
    refresh: 'تحديث',
    apply: 'تطبيق',
    cancel: 'إلغاء',
    close: 'إغلاق',
    save: 'حفظ',
    delete: 'حذف',
    reset: 'إعادة للوضع التلقائي',
    export: 'تصدير CSV',
    syncMeta: 'مزامنة نطاق Meta',
    syncing: 'جارٍ المزامنة…',
    inspect: 'تفاصيل',
    compare: 'مقارنة',
    previousPeriod: 'مقارنة بالفترة السابقة',
    noComparison: 'لا توجد فترة سابقة',
    noData: 'لا توجد بيانات موثوقة لهذا الاختيار.',
    partialPeriod: 'فترة مفتوحة',
    exactRows: 'القيم الدقيقة',
    sourceHealth: 'مصادر البيانات',
    sourceNote: 'التغطية جزء من المقياس وليست ملاحظة جانبية.',
    ranges: {
      '7d': '7 أيام',
      '14d': '14 يومًا',
      '30d': '30 يومًا',
      '90d': '90 يومًا',
      year: 'السنة',
      all: 'الكل',
      custom: 'مخصص',
    },
    grains: { auto: 'تلقائي', day: 'يومي', week: 'أسابيع الجمعة', month: 'شهري' },
    metrics: {
      trueProfit: 'الربح الحقيقي',
      profitX: 'مضاعف الربح',
      adjustedProfit: 'الربح المعدل',
      automaticPaidProfit: 'ربح الطلبات المدفوعة',
      paidProfitCoverage: 'تغطية تكلفة الطلبات المدفوعة',
      adCost: 'تكلفة Meta',
      postedOrders: 'الطلبات المرسلة',
      postedUnits: 'الوحدات المرسلة',
      paidUnits: 'الوحدات المدفوعة',
      costPerPosted: 'تكلفة / مرسلة',
      costPerDelivered: 'تكلفة / مسلمة',
      costPerPaid: 'تكلفة / مدفوعة',
      submittedOrders: 'الطلبات المسجلة',
      paidOrders: 'الطلبات المدفوعة',
      storefrontConversion: 'تحويل المتجر',
      impressions: 'مرات الظهور',
      outboundClicks: 'النقرات الصادرة',
      landingPageViews: 'زيارات الهبوط',
      activeShipments: 'الشحنات النشطة',
      observedReturnRate: 'نسبة الإرجاع الناضجة',
      sessions: 'الجلسات',
      engagementRate: 'التفاعل',
      purchases: 'الطلبات المسجلة',
      conversionRate: 'التحويل',
      errorRate: 'نسبة الأخطاء',
      returningJourneys: 'الزيارات المتكررة',
      productProfit: 'مرجع ربح التسوية',
      unitsSold: 'الوحدات المباعة',
      customers: 'العملاء',
      repeatRate: 'نسبة التكرار',
      activeMonthlyBurn: 'التكلفة الشهرية',
      periodOperatingCost: 'تكاليف الفترة',
      manualOverrideDays: 'أيام معدلة',
      projectedCoverage: 'تغطية التكلفة',
      searchClicks: 'نقرات Google',
      searchImpressions: 'مرات الظهور في البحث',
      searchCtr: 'نسبة النقر',
      averagePosition: 'متوسط الترتيب',
    },
    sections: {
      trajectory: 'مسار النشاط',
      signals: 'قائمة المتابعة',
      commerceFunnel: 'نضج الطلبات',
      cashPipeline: 'مسار السيولة',
      paidEconomics: 'اقتصاد الدفع التلقائي',
      reconciliation: 'مرجع التسوية',
      forecast: 'النظرة المستقبلية',
      moneyPerformance: 'الأداء المالي',
      weeklyEconomics: 'أسابيع تبدأ الجمعة',
      economicsLedger: 'السجل المالي',
      profitEfficiency: 'كفاءة الربح',
      creativeFatigue: 'إجهاد الإعلانات',
      creativeResponse: 'استجابة المحتوى',
      paidFunnel: 'قمع الإعلانات',
      hierarchy: 'هيكل الحملات',
      trackingHealth: 'سلامة التتبع',
      deliveryPipeline: 'مسار التوصيل',
      shipmentStates: 'حالات الشحن',
      exceptionQueue: 'قائمة الاستثناءات',
      cycleTime: 'زمن الدورة',
      attempts: 'المحاولات والنتيجة',
      cohorts: 'أفواج الطلبات المرسلة',
      siteTrend: 'اتجاه المتجر',
      searchTrend: 'الطلب عبر البحث',
      searchOpportunities: 'قائمة الفرص',
      searchPages: 'ظهور صفحات الهبوط',
      searchMix: 'مزيج الاكتشاف',
      indexHealth: 'صحة الفهرسة',
      siteFunnel: 'قمع المتجر',
      paths: 'المسارات الحديثة',
      searches: 'طلب البحث',
      landingPages: 'صفحات الهبوط',
      experience: 'جودة التجربة',
      products: 'ذكاء المنتجات',
      basketPairs: 'منتجات تشترى معًا',
      geography: 'المناطق والتوصيل',
      customerBase: 'قاعدة العملاء',
      planningReturns: 'نسبة الإرجاع المخططة',
      operatingCosts: 'تكاليف التشغيل',
      dailyOverrides: 'التعديلات اليومية',
      formula: 'المعادلة الأساسية',
      automationEvidence: 'الأتمتة مقابل التسويات',
    },
    sources: {
      orders: 'الطلبات',
      ecotrack: 'EcoTrack',
      meta: 'Meta',
      storefront: 'المتجر',
      searchConsole: 'بحث Google',
      settlements: 'التسويات',
      assumptions: 'افتراضات يدوية',
    },
    sourceStates: {
      live: 'مباشر',
      current: 'حالي',
      lagged: 'متأخر',
      manual: 'يدوي',
      partial: 'جزئي',
      missing: 'مفقود',
    },
    signalLabels: {
      belowBreakEven: 'مضاعف الربح دون نقطة التعادل',
      aboveBreakEven: 'مضاعف الربح فوق نقطة التعادل',
      returnAssumptionGap: 'المرتجعات المرصودة تختلف عن التخطيط',
      costCoverageGap: 'بيانات تكلفة الشراء غير مكتملة',
      fridayPending: 'إنفاق الجمعة ينتظر الترحيل',
      activePipeline: 'طلبات ما زالت في مسار التوصيل',
    },
    warningLabels: {
      sourceMissing: 'مصدر مفقود لهذه الفترة',
      sourcePartial: 'مصدر يغطي جزءًا فقط من الفترة',
      projectedCostCoverage: 'الربح المتوقع يستخدم هامشًا احتياطيًا بنسبة 30٪',
      pendingFridayRollforward: 'إنفاق Meta للجمعة ينتظر الترحيل',
      pathRetentionPartial: 'تفاصيل المسارات محدودة بمدة الاحتفاظ بالأحداث',
      searchDetailCoverage: 'تفاصيل الاستعلام والصفحة محدودة بخصوصية Google',
    },
    columns: {
      date: 'التاريخ',
      value: 'القيمة',
      status: 'الحالة',
      orders: 'الطلبات',
      spend: 'الإنفاق',
      profit: 'الربح',
      trueProfit: 'الربح الحقيقي',
      profitX: 'مضاعف الربح',
      operatingCost: 'تكاليف التشغيل',
      grossProfit: 'الربح الخام',
      adjustedProfit: 'الربح المعدل',
      adCost: 'تكلفة الإعلان',
      netProfit: 'صافي الربح',
      coverage: 'التغطية',
      name: 'الاسم',
      campaign: 'الحملة',
      impressions: 'الظهور',
      ctr: 'CTR',
      outboundCtr: 'CTR الصادر',
      cpm: 'CPM',
      landingViews: 'زيارات الهبوط',
      videoCompletion: 'اكتمال الفيديو',
      watchTime: 'متوسط المشاهدة',
      ranking: 'الترتيب',
      confirmed: 'مؤكدة',
      posted: 'مرسلة',
      paid: 'مدفوعة',
      returned: 'مرتجعة',
      costPerPosted: 'تكلفة / مرسلة',
      share: 'الحصة',
      stale: 'متوقفة >48س',
      age: 'متوسط العمر',
      p50: 'الوسيط',
      p75: 'P75',
      p90: 'P90',
      sample: 'العينة',
      sessions: 'الجلسات',
      conversion: 'التحويل',
      views: 'المشاهدات',
      carts: 'السلات',
      revenue: 'الإيراد',
      units: 'الوحدات',
      margin: 'الهامش',
      category: 'الفئة',
      brand: 'العلامة',
      first: 'الأول',
      second: 'الثاني',
      repeat: 'التكرار',
      source: 'المصدر',
      note: 'ملاحظة',
      query: 'عبارة البحث',
      page: 'الصفحة',
      clicks: 'النقرات',
      position: 'الترتيب',
      potential: 'نقرات محتملة',
      device: 'الجهاز',
      country: 'الدولة',
    },
    modes: {
      projected: 'متوقع',
      realized: 'مدفوع فعلي',
      cumulative: 'تراكمي',
      daily: 'يومي',
      campaign: 'الحملات',
      adset: 'المجموعات',
      ad: 'الإعلانات',
    },
    cashStages: {
      submitted: 'مُرسلة · غير مؤكدة',
      confirmed: 'مؤكدة · غير منشورة',
      inTransit: 'قيد النقل',
      deliveredAwaitingCollection: 'تم التسليم · بانتظار التحصيل',
      collectedAwaitingPayout: 'تم التحصيل · بانتظار الدفع',
      paymentReady: 'الدفع جاهز',
      paid: 'مدفوع ومؤرشف',
    },
    expectedToPost: 'متوقع نشرها',
    returnCopy: {
      planning: 'نسبة التخطيط',
      mature: 'المرصود الناضج',
      terminal: 'كل النتائج النهائية',
      useMature: 'استخدام النسبة الناضجة',
      useTerminal: 'استخدام كل النتائج',
      caveat: 'يظهر التاريخ المرصود كدليل ولا يغيّر نسبة التخطيط إلا باختيارك.',
    },
    assumptions: {
      fx: 'سعر EUR → DZD',
      defaultReturn: 'نسبة الإرجاع الافتراضية',
      restFrom: 'بدء راحة الجمعة',
      newCost: 'إضافة تكلفة',
      monthly: 'شهري',
      once: 'مرة واحدة',
      amount: 'المبلغ DZD',
      start: 'تاريخ البدء',
      end: 'تاريخ النهاية (اختياري)',
      newOverride: 'تعديل اليوم',
      gross: 'الربح الخام DZD',
      confirmed: 'الطلبات المؤكدة',
      returnRate: 'نسبة الإرجاع %',
      notes: 'ملاحظة المشغل',
      automatic: 'تلقائي',
      manual: 'يدوي',
      missing: 'مفقود',
    },
  },
} as const;

export type Analytics2Copy = (typeof analytics2Copy)['en'];

export function getAnalytics2Copy(locale: string): Analytics2Copy {
  const key = locale.startsWith('ar') ? 'ar' : locale.startsWith('fr') ? 'fr' : 'en';
  return analytics2Copy[key] as unknown as Analytics2Copy;
}
