const analytics2Copy = {
  en: {
    loading: 'Updating this view…',
    updated: 'Updated',
    refresh: 'Refresh',
    apply: 'Apply',
    cancel: 'Cancel',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    reset: 'Reset to automatic',
    export: 'Export CSV',
    syncMeta: 'Sync Meta range',
    syncing: 'Synchronizing…',
    inspect: 'Inspect',
    compare: 'Compare',
    previousPeriod: 'vs previous period',
    noComparison: 'No comparable period',
    noData: 'No trustworthy data for this selection.',
    partialPeriod: 'Open period',
    exactRows: 'Exact values',
    sourceHealth: 'Data sources',
    sourceNote: 'Coverage is part of the metric, not a footnote.',
    ranges: {
      '7d': '7 days',
      '14d': '14 days',
      '30d': '30 days',
      '90d': '90 days',
      year: 'Year',
      all: 'All',
      custom: 'Custom',
    },
    grains: { auto: 'Auto grain', day: 'Daily', week: 'Friday weeks', month: 'Monthly' },
    metrics: {
      trueProfit: 'True profit',
      profitX: 'Profit ×',
      adjustedProfit: 'Adjusted profit',
      automaticPaidProfit: 'Paid-order profit',
      paidProfitCoverage: 'Exact paid-cost coverage',
      adCost: 'Meta cost',
      postedOrders: 'Posted orders',
      postedUnits: 'Posted units',
      paidUnits: 'Paid units',
      costPerPosted: 'Cost / posted',
      costPerDelivered: 'Cost / delivered',
      costPerPaid: 'Cost / paid',
      submittedOrders: 'Submitted orders',
      paidOrders: 'Paid orders',
      storefrontConversion: 'Store conversion',
      impressions: 'Impressions',
      outboundClicks: 'Outbound clicks',
      landingPageViews: 'Landing views',
      activeShipments: 'Active shipments',
      observedReturnRate: 'Mature return rate',
      sessions: 'Sessions',
      engagementRate: 'Engagement',
      purchases: 'Orders placed',
      conversionRate: 'Conversion',
      errorRate: 'Error rate',
      returningJourneys: 'Returning journeys',
      productProfit: 'Settlement profit reference',
      unitsSold: 'Units sold',
      customers: 'Customers',
      repeatRate: 'Repeat rate',
      activeMonthlyBurn: 'Monthly burn',
      periodOperatingCost: 'Period operating cost',
      manualOverrideDays: 'Override days',
      projectedCoverage: 'Cost coverage',
      searchClicks: 'Google clicks',
      searchImpressions: 'Search impressions',
      searchCtr: 'Search CTR',
      averagePosition: 'Average position',
    },
    sections: {
      trajectory: 'Profit',
      signals: 'Signals',
      commerceFunnel: 'Order maturity',
      cashPipeline: 'Cash pipeline',
      paidEconomics: 'Paid economics',
      reconciliation: 'Settlement reference',
      forecast: 'Forward view',
      moneyPerformance: 'Financial performance',
      weeklyEconomics: 'Friday-start weeks',
      economicsLedger: 'Economics ledger',
      profitEfficiency: 'Profit efficiency',
      creativeFatigue: 'Creative fatigue',
      creativeResponse: 'Creative response',
      paidFunnel: 'Paid funnel',
      hierarchy: 'Campaign hierarchy',
      trackingHealth: 'Tracking health',
      deliveryPipeline: 'Delivery pipeline',
      shipmentStates: 'Shipment states',
      exceptionQueue: 'Exception queue',
      cycleTime: 'Cycle time',
      attempts: 'Attempts versus outcome',
      cohorts: 'Posted-order cohorts',
      siteTrend: 'Storefront trend',
      searchTrend: 'Search demand',
      searchOpportunities: 'Opportunity queue',
      searchPages: 'Landing-page visibility',
      searchMix: 'Discovery mix',
      indexHealth: 'Index health',
      siteFunnel: 'Storefront funnel',
      paths: 'Recent paths',
      searches: 'Search demand',
      landingPages: 'Landing pages',
      experience: 'Experience quality',
      products: 'Product intelligence',
      basketPairs: 'Products bought together',
      geography: 'Geography and delivery',
      customerBase: 'Customer base',
      planningReturns: 'Planning return rate',
      operatingCosts: 'Operating costs',
      dailyOverrides: 'Daily source overrides',
      formula: 'Canonical formula',
      automationEvidence: 'Automation versus settlement evidence',
    },
    sources: {
      orders: 'Orders',
      ecotrack: 'EcoTrack',
      meta: 'Meta',
      storefront: 'Storefront',
      searchConsole: 'Google Search',
      settlements: 'Settlements',
      assumptions: 'Manual assumptions',
    },
    sourceStates: {
      live: 'Live',
      current: 'Current',
      lagged: 'Lagged',
      manual: 'Manual',
      partial: 'Partial',
      missing: 'Missing',
    },
    signalLabels: {
      belowBreakEven: 'Profit × is below break-even',
      aboveBreakEven: 'Profit × is above break-even',
      returnAssumptionGap: 'Observed returns differ from planning',
      costCoverageGap: 'Purchase-cost snapshots are incomplete',
      fridayPending: 'Friday spend awaits roll-forward',
      activePipeline: 'Orders are still moving through delivery',
    },
    warningLabels: {
      sourceMissing: 'A source is missing for this range',
      sourcePartial: 'A source only covers part of this range',
      projectedCostCoverage: 'Projected profit uses a 30% fallback margin for missing costs',
      pendingFridayRollforward: 'Friday Meta spend is pending roll-forward',
      pathRetentionPartial: 'Path detail is limited by raw-event retention',
      searchDetailCoverage: 'Query and page detail is privacy-limited by Google',
    },
    columns: {
      date: 'Date',
      value: 'Value',
      status: 'Status',
      orders: 'Orders',
      spend: 'Spend',
      profit: 'Profit',
      trueProfit: 'True profit',
      profitX: 'Profit ×',
      operatingCost: 'Operating costs',
      grossProfit: 'Gross profit',
      adjustedProfit: 'Adjusted profit',
      adCost: 'Ad cost',
      netProfit: 'Net profit',
      coverage: 'Coverage',
      name: 'Name',
      campaign: 'Campaign',
      impressions: 'Impressions',
      ctr: 'CTR',
      outboundCtr: 'Outbound CTR',
      cpm: 'CPM',
      landingViews: 'Landing views',
      videoCompletion: 'Video complete',
      watchTime: 'Avg watch',
      ranking: 'Ranking',
      confirmed: 'Confirmed',
      posted: 'Posted',
      paid: 'Paid',
      returned: 'Returned',
      costPerPosted: 'Cost / posted',
      share: 'Share',
      stale: 'Stale >48h',
      age: 'Median age',
      p50: 'Median',
      p75: 'P75',
      p90: 'P90',
      sample: 'Sample',
      sessions: 'Sessions',
      conversion: 'Conversion',
      views: 'Views',
      carts: 'Carts',
      revenue: 'Revenue',
      units: 'Units',
      margin: 'Margin',
      category: 'Category',
      brand: 'Brand',
      first: 'First',
      second: 'Second',
      repeat: 'Repeat',
      source: 'Source',
      note: 'Note',
      query: 'Query',
      page: 'Page',
      clicks: 'Clicks',
      position: 'Position',
      potential: 'Potential clicks',
      device: 'Device',
      country: 'Country',
    },
    labels: {
      ecoTrackFee: 'EcoTrack fee',
      paidCod: 'Paid COD',
      estimatedFees: 'Estimated fees',
      netRecovered: 'Net recovered',
      cod: 'COD',
      fees: 'Fees',
      providerCod: 'Provider COD',
      profitMaturation: 'Profit maturation',
      projectedTrueProfit: 'Projected true profit',
      deliveredTrueProfit: 'Delivered true profit',
      paidTrueProfit: 'Paid true profit',
      postingWeek: 'Posting week',
      posted: 'Posted',
      delivered: 'Delivered',
      paid: 'Paid',
      projected: 'Projected',
      paidProfit: 'Paid profit',
      variance: 'Variance',
      maturity: 'Maturity',
      open: 'Open',
      upper: 'Upper',
      lower: 'Lower',
      beforeReturns: 'Before returns',
      afterReturns: 'After returns',
      playRate: 'Play rate',
      completion: 'Completion',
      averageWatch: 'Average watch',
      outboundCtr: 'Outbound CTR',
      confirmationRate: 'Confirmation rate',
      clickToPage: 'Click → page',
      metaPurchases: 'Meta purchases',
      firstPartyOrders: 'First-party orders',
      exactAdIdCoverage: 'Exact ad-ID coverage',
      outcomeMaturity: 'Outcome maturity',
      campaignMaturation: 'Campaign maturation',
      costPerPosted: 'Cost / posted',
      costPerDelivered: 'Cost / delivered',
      costPerPaid: 'Cost / paid',
      metaSpend: 'Meta spend',
      adCostDzd: 'Ad cost DZD',
      outcomeWindowCost: 'Outcome-window cost',
      outcomeSpendCoverage: 'Outcome spend coverage',
      impressions: 'Impressions',
      outboundClicks: 'Outbound clicks',
      uniqueOutbound: 'Unique outbound',
      landingViews: 'Landing views',
      landingViewRate: 'Landing-view rate',
      videoPlays: 'Video plays',
      videoCompletion: 'Video completion',
      qualityRanking: 'Quality ranking',
      engagementRanking: 'Engagement ranking',
      conversionRanking: 'Conversion ranking',
      bricOrders: 'Bric orders',
      confirmed: 'Confirmed',
      returned: 'Returned',
      projectedProfitX: 'Projected Profit ×',
      paidProfitX: 'Paid Profit ×',
      profitCoverage: 'Profit coverage',
      manualModelInput: 'Manual model input',
      active: 'Active',
      errors: 'Errors',
      productViewToCartSessions: 'Product-view → cart sessions',
      checkoutToSubmittedOrder: 'Checkout → submitted order',
      from: 'From',
      to: 'To',
      aiAssistedShopping: 'AI-assisted shopping',
      opens: 'Opens',
      messages: 'Messages',
      resultClicks: 'Result clicks',
      influencedOrders: 'Influenced orders',
      opportunity: 'Opportunity',
      searchLandingPagesDescription:
        'Landing pages as Google sees them. Select a row to inspect the queries creating its visibility.',
      queries: 'Queries',
      devices: 'Devices',
      countries: 'Countries',
      sitemap: 'Sitemap',
      inspectedSample: 'Inspected sample',
      searchOpportunityEvidence: 'Search opportunity evidence',
      currentCtr: 'Current CTR',
      comparableCtr: 'Comparable CTR',
      googleLandingPageEvidence: 'Google landing-page evidence',
      productViews: 'Product views',
      terminalPaid: 'Terminal paid',
      paidReturned: 'Paid / returned',
      stillActive: 'Still active',
      scatterViews: 'Views →',
      scatterPaidOutcome: 'Paid outcome ↑',
      bubbleResolvedOrders: 'Bubble · resolved orders',
      terminalPaidRate: 'Terminal paid rate',
      postedUnits: 'Posted units',
      projectedContribution: 'Projected contribution',
      delivery: 'Delivery',
      wilaya: 'Wilaya',
      attempts: 'Attempts',
      pipelineCod: 'Pipeline COD',
      commune: 'Commune',
      customers: 'Customers',
      customer: 'Customer',
      city: 'City',
      submitted: 'Submitted',
      paidRevenue: 'Paid revenue',
      contribution: 'Contribution',
      margin: 'Margin',
      postedOrders: 'Posted orders',
      paidOrders: 'Paid orders',
      returnedOrders: 'Returned orders',
      costCoverage: 'Cost coverage',
      medianDelivery: 'Median delivery',
      units: 'Units',
      economicControls: 'Economic controls',
      period: 'Period',
      returnPercent: 'Return %',
      blankFieldsDefer: 'Blank fields defer independently to the automatic source.',
      orders: 'orders',
      terminal: 'terminal',
      eligible: 'eligible',
      resolved: 'resolved',
      postingCohorts: 'posting cohorts',
      terminalOrders: 'terminal orders',
      metaInsightsSynchronized: 'Meta insights synchronized.',
      googleSearchSynchronized: 'Google Search data synchronized.',
      syncFailed: 'Synchronization failed.',
      syncGoogle: 'Sync Google',
      played: 'Played',
      completed: 'Completed',
      outcomeWindow: 'outcome window',
      events: 'events',
      unavailable: 'unavailable',
      failed: 'failed',
      noEvent: 'No event',
      rawEventWindow: 'raw-event window',
      empty: '(empty)',
      zeroResultsShort: 'zero results',
      samples: 'samples',
      poor: 'poor',
      sessions: 'sessions',
      clicks: 'clicks',
      position: 'position',
      rankingPages: 'ranking pages',
      brand: 'brand',
      discovery: 'discovery',
      nearPageOne: 'Near page one',
      ctrGap: 'CTR gap',
      contentGap: 'Content gap',
      searchAppearance: 'Search appearance',
      urls: 'URLs',
      warnings: 'warnings',
      downloaded: 'downloaded',
      noUrlsInspected: 'No URLs inspected',
      pagesNeedReview: 'pages need review',
      noActionableIssue: 'No actionable issue in the current sample',
      openPublicPage: 'Open public page',
      searchProduct: 'Search product, SKU or category',
      above: 'Above',
      below: 'Below',
      insufficientProductOutcomes:
        'Not enough resolved product outcomes for a reliable comparison.',
      noSku: 'No SKU',
      uncategorized: 'Uncategorized',
      metaReportedRegions: 'Meta-reported regions',
      aggregateMediaGeography: 'Aggregate media geography · not joined to customer wilayas',
      untracked: 'untracked',
      provider: 'provider',
      secondOrderConversion: 'Second-order conversion',
      exactMetaAssociations: 'Exact Meta associations',
      unknownCampaign: 'Unknown campaign',
      unknownAdSet: 'Unknown ad set',
      noExactAdAssociation: 'No exact ad-ID association in this range.',
      periodChange: 'Period change',
      assumptionsSaved: 'Assumptions saved.',
      operatingCostUpdated: 'Operating cost updated.',
      operatingCostAdded: 'Operating cost added.',
      operatingCostRemoved: 'Operating cost removed.',
      dailyOverrideSaved: 'Daily override saved.',
      dailyValuesReset: 'Daily values returned to automatic sources.',
      cpmEur: 'CPM EUR',
      analyticsRange: 'Analytics range',
      analyticsGrain: 'Analytics grain',
      startDate: 'Start date',
      endDate: 'End date',
      analyticsRequestFailed: 'Analytics request failed.',
      productViewSessions: 'Product-view sessions',
      cartSessions: 'Cart sessions',
      checkoutSessions: 'Checkout sessions',
      submittedOrderSessions: 'Submitted-order sessions',
      nextSevenDayModel: 'Next 7-day model',
    },
    modes: {
      projected: 'Projected',
      realized: 'Paid actual',
      cumulative: 'Cumulative',
      daily: 'Daily',
      campaign: 'Campaigns',
      adset: 'Ad sets',
      ad: 'Ads',
    },
    cashStages: {
      submitted: 'Submitted · unconfirmed',
      confirmed: 'Confirmed · unposted',
      inTransit: 'In transit',
      deliveredAwaitingCollection: 'Delivered · awaiting collection',
      collectedAwaitingPayout: 'Collected · awaiting payout',
      paymentReady: 'Payment ready',
      paid: 'Paid & archived',
    },
    fulfillmentPhases: {
      paid: 'Paid',
      return: 'Returned',
      cancelled: 'Cancelled',
      cash: 'Awaiting payment',
      delivery: 'Out for delivery',
      transit: 'In transit',
      ready: 'Ready to ship',
      exception: 'Needs review',
      untracked: 'Untracked',
    },
    expectedToPost: 'expected to post',
    returnCopy: {
      planning: 'Planning rate',
      mature: 'Mature observed',
      terminal: 'All terminal',
      useMature: 'Use mature rate',
      useTerminal: 'Use all-terminal rate',
      caveat:
        'Observed history is shown as evidence. It never changes the planning percentage unless you choose it.',
    },
    assumptions: {
      fx: 'EUR → DZD rate',
      defaultReturn: 'Default return rate',
      restFrom: 'Friday-rest active from',
      newCost: 'Add operating cost',
      monthly: 'Monthly',
      once: 'One time',
      amount: 'Amount DZD',
      start: 'Start date',
      end: 'End date (optional)',
      newOverride: 'Edit daily override',
      gross: 'Gross profit DZD',
      confirmed: 'Confirmed orders',
      returnRate: 'Return rate %',
      notes: 'Operator note',
      automatic: 'Automatic',
      manual: 'Manual',
      missing: 'Missing',
    },
  },
  fr: {
    loading: 'Mise à jour de la vue…',
    updated: 'Mis à jour',
    refresh: 'Actualiser',
    apply: 'Appliquer',
    cancel: 'Annuler',
    close: 'Fermer',
    save: 'Enregistrer',
    delete: 'Supprimer',
    reset: 'Revenir à l’automatique',
    export: 'Exporter CSV',
    syncMeta: 'Synchroniser la période Meta',
    syncing: 'Synchronisation…',
    inspect: 'Inspecter',
    compare: 'Comparer',
    previousPeriod: 'vs période précédente',
    noComparison: 'Aucune comparaison antérieure',
    noData: 'Aucune donnée fiable pour cette sélection.',
    partialPeriod: 'Période ouverte',
    exactRows: 'Valeurs exactes',
    sourceHealth: 'Sources de données',
    sourceNote: 'La couverture fait partie de la métrique, pas d’une note de bas de page.',
    ranges: {
      '7d': '7 jours',
      '14d': '14 jours',
      '30d': '30 jours',
      '90d': '90 jours',
      year: 'Année',
      all: 'Tout',
      custom: 'Personnalisé',
    },
    grains: { auto: 'Grain auto', day: 'Quotidien', week: 'Semaines vendredi', month: 'Mensuel' },
    metrics: {
      trueProfit: 'Profit réel',
      profitX: 'Profit ×',
      adjustedProfit: 'Profit ajusté',
      automaticPaidProfit: 'Profit des commandes payées',
      paidProfitCoverage: 'Couverture exacte des coûts payés',
      adCost: 'Coût Meta',
      postedOrders: 'Commandes expédiées',
      postedUnits: 'Unités expédiées',
      paidUnits: 'Unités payées',
      costPerPosted: 'Coût / expédiée',
      costPerDelivered: 'Coût / livrée',
      costPerPaid: 'Coût / payée',
      submittedOrders: 'Commandes saisies',
      paidOrders: 'Commandes payées',
      storefrontConversion: 'Conversion boutique',
      impressions: 'Impressions',
      outboundClicks: 'Clics sortants',
      landingPageViews: 'Vues de destination',
      activeShipments: 'Envois actifs',
      observedReturnRate: 'Retour mature',
      sessions: 'Sessions',
      engagementRate: 'Engagement',
      purchases: 'Commandes saisies',
      conversionRate: 'Conversion',
      errorRate: 'Taux d’erreur',
      returningJourneys: 'Parcours récurrents',
      productProfit: 'Référence de profit réglé',
      unitsSold: 'Unités vendues',
      customers: 'Clients',
      repeatRate: 'Taux de retour client',
      activeMonthlyBurn: 'Charge mensuelle',
      periodOperatingCost: 'Coûts de période',
      manualOverrideDays: 'Jours corrigés',
      projectedCoverage: 'Couverture des coûts',
      searchClicks: 'Clics Google',
      searchImpressions: 'Impressions de recherche',
      searchCtr: 'CTR de recherche',
      averagePosition: 'Position moyenne',
    },
    sections: {
      trajectory: 'Trajectoire de l’activité',
      signals: 'File opérateur',
      commerceFunnel: 'Maturité des commandes',
      cashPipeline: 'Pipeline de trésorerie',
      paidEconomics: 'Économie payée automatique',
      reconciliation: 'Référence de règlement',
      forecast: 'Projection',
      moneyPerformance: 'Performance financière',
      weeklyEconomics: 'Semaines débutant vendredi',
      economicsLedger: 'Registre économique',
      profitEfficiency: 'Efficacité du profit',
      creativeFatigue: 'Fatigue créative',
      creativeResponse: 'Réponse créative',
      paidFunnel: 'Entonnoir payant',
      hierarchy: 'Hiérarchie des campagnes',
      trackingHealth: 'Santé du tracking',
      deliveryPipeline: 'Pipeline de livraison',
      shipmentStates: 'États des envois',
      exceptionQueue: 'File des exceptions',
      cycleTime: 'Temps de cycle',
      attempts: 'Tentatives et résultat',
      cohorts: 'Cohortes de commandes expédiées',
      siteTrend: 'Tendance boutique',
      searchTrend: 'Demande de recherche',
      searchOpportunities: 'File d’opportunités',
      searchPages: 'Visibilité des pages',
      searchMix: 'Mix de découverte',
      indexHealth: 'Santé de l’index',
      siteFunnel: 'Entonnoir boutique',
      paths: 'Parcours récents',
      searches: 'Demande de recherche',
      landingPages: 'Landing pages',
      experience: 'Qualité de l’expérience',
      products: 'Intelligence produit',
      basketPairs: 'Produits achetés ensemble',
      geography: 'Zones et livraison',
      customerBase: 'Base clients',
      planningReturns: 'Taux de retour planifié',
      operatingCosts: 'Coûts d’exploitation',
      dailyOverrides: 'Corrections quotidiennes',
      formula: 'Formule canonique',
      automationEvidence: 'Automatisation face aux règlements',
    },
    sources: {
      orders: 'Commandes',
      ecotrack: 'EcoTrack',
      meta: 'Meta',
      storefront: 'Boutique',
      searchConsole: 'Recherche Google',
      settlements: 'Règlements',
      assumptions: 'Hypothèses manuelles',
    },
    sourceStates: {
      live: 'Direct',
      current: 'À jour',
      lagged: 'En retard',
      manual: 'Manuel',
      partial: 'Partiel',
      missing: 'Absent',
    },
    signalLabels: {
      belowBreakEven: 'Profit × sous le seuil de rentabilité',
      aboveBreakEven: 'Profit × au-dessus du seuil',
      returnAssumptionGap: 'Les retours observés diffèrent du plan',
      costCoverageGap: 'Snapshots de coût d’achat incomplets',
      fridayPending: 'Dépense du vendredi en attente de report',
      activePipeline: 'Des commandes sont encore en livraison',
    },
    warningLabels: {
      sourceMissing: 'Une source manque sur cette période',
      sourcePartial: 'Une source ne couvre qu’une partie de la période',
      projectedCostCoverage: 'Le profit projeté utilise une marge de secours de 30 %',
      pendingFridayRollforward: 'La dépense Meta du vendredi attend son report',
      pathRetentionPartial: 'Les parcours détaillés sont limités par la rétention des événements',
      searchDetailCoverage: 'Le détail requête/page est limité par la confidentialité Google',
    },
    columns: {
      date: 'Date',
      value: 'Valeur',
      status: 'État',
      orders: 'Commandes',
      spend: 'Dépense',
      profit: 'Profit',
      trueProfit: 'Profit réel',
      profitX: 'Profit ×',
      operatingCost: 'Coûts opérationnels',
      grossProfit: 'Profit brut',
      adjustedProfit: 'Profit ajusté',
      adCost: 'Coût pub',
      netProfit: 'Profit net',
      coverage: 'Couverture',
      name: 'Nom',
      campaign: 'Campagne',
      impressions: 'Impressions',
      ctr: 'CTR',
      outboundCtr: 'CTR sortant',
      cpm: 'CPM',
      landingViews: 'Vues destination',
      videoCompletion: 'Vidéo complète',
      watchTime: 'Visionnage moyen',
      ranking: 'Classement',
      confirmed: 'Confirmées',
      posted: 'Expédiées',
      paid: 'Payées',
      returned: 'Retournées',
      costPerPosted: 'Coût / expédiée',
      share: 'Part',
      stale: 'Bloquées >48 h',
      age: 'Âge médian',
      p50: 'Médiane',
      p75: 'P75',
      p90: 'P90',
      sample: 'Échantillon',
      sessions: 'Sessions',
      conversion: 'Conversion',
      views: 'Vues',
      carts: 'Paniers',
      revenue: 'Revenu',
      units: 'Unités',
      margin: 'Marge',
      category: 'Catégorie',
      brand: 'Marque',
      first: 'Premier',
      second: 'Second',
      repeat: 'Récurrence',
      source: 'Source',
      note: 'Note',
      query: 'Requête',
      page: 'Page',
      clicks: 'Clics',
      position: 'Position',
      potential: 'Clics potentiels',
      device: 'Appareil',
      country: 'Pays',
    },
    labels: {
      ecoTrackFee: 'Frais EcoTrack',
      paidCod: 'COD payé',
      estimatedFees: 'Frais estimés',
      netRecovered: 'Montant net récupéré',
      cod: 'COD',
      fees: 'Frais',
      providerCod: 'COD transporteur',
      profitMaturation: 'Maturation du profit',
      projectedTrueProfit: 'Profit réel projeté',
      deliveredTrueProfit: 'Profit réel livré',
      paidTrueProfit: 'Profit réel payé',
      postingWeek: 'Semaine de publication',
      posted: 'Publiées',
      delivered: 'Livrées',
      paid: 'Payées',
      projected: 'Projeté',
      paidProfit: 'Profit payé',
      variance: 'Écart',
      maturity: 'Maturité',
      open: 'Ouverte',
      upper: 'Haute',
      lower: 'Basse',
      beforeReturns: 'Avant retours',
      afterReturns: 'Après retours',
      playRate: 'Taux de lecture',
      completion: 'Complétion',
      averageWatch: 'Visionnage moyen',
      outboundCtr: 'CTR sortant',
      confirmationRate: 'Taux de confirmation',
      clickToPage: 'Clic → page',
      metaPurchases: 'Achats Meta',
      firstPartyOrders: 'Commandes first-party',
      exactAdIdCoverage: 'Couverture exacte des ID publicitaires',
      outcomeMaturity: 'Maturité des résultats',
      campaignMaturation: 'Maturation des campagnes',
      costPerPosted: 'Coût / publiée',
      costPerDelivered: 'Coût / livrée',
      costPerPaid: 'Coût / payée',
      metaSpend: 'Dépenses Meta',
      adCostDzd: 'Coût publicitaire DZD',
      outcomeWindowCost: 'Coût de la fenêtre de résultat',
      outcomeSpendCoverage: 'Couverture des dépenses attribuées',
      impressions: 'Impressions',
      outboundClicks: 'Clics sortants',
      uniqueOutbound: 'Clics sortants uniques',
      landingViews: 'Vues de destination',
      landingViewRate: 'Taux de vue de destination',
      videoPlays: 'Lectures vidéo',
      videoCompletion: 'Complétion vidéo',
      qualityRanking: 'Classement qualité',
      engagementRanking: 'Classement engagement',
      conversionRanking: 'Classement conversion',
      bricOrders: 'Commandes Bric',
      confirmed: 'Confirmées',
      returned: 'Retournées',
      projectedProfitX: 'Profit × projeté',
      paidProfitX: 'Profit × payé',
      profitCoverage: 'Couverture du profit',
      manualModelInput: 'Entrée manuelle du modèle',
      active: 'Actives',
      errors: 'Erreurs',
      productViewToCartSessions: 'Vue produit → panier',
      checkoutToSubmittedOrder: 'Paiement → commande soumise',
      from: 'De',
      to: 'Vers',
      aiAssistedShopping: 'Achats assistés par IA',
      opens: 'Ouvertures',
      messages: 'Messages',
      resultClicks: 'Clics sur résultat',
      influencedOrders: 'Commandes influencées',
      opportunity: 'Opportunité',
      searchLandingPagesDescription:
        'Pages de destination vues par Google. Sélectionnez une ligne pour examiner les requêtes qui créent sa visibilité.',
      queries: 'Requêtes',
      devices: 'Appareils',
      countries: 'Pays',
      sitemap: 'Plan du site',
      inspectedSample: 'Échantillon inspecté',
      searchOpportunityEvidence: 'Preuves de l’opportunité de recherche',
      currentCtr: 'CTR actuel',
      comparableCtr: 'CTR comparable',
      googleLandingPageEvidence: 'Preuves Google de la page de destination',
      productViews: 'Vues produit',
      terminalPaid: 'Payées terminales',
      paidReturned: 'Payées / retournées',
      stillActive: 'Encore actives',
      scatterViews: 'Vues →',
      scatterPaidOutcome: 'Résultat payé ↑',
      bubbleResolvedOrders: 'Bulle · commandes résolues',
      terminalPaidRate: 'Taux payé terminal',
      postedUnits: 'Unités publiées',
      projectedContribution: 'Contribution projetée',
      delivery: 'Livraison',
      wilaya: 'Wilaya',
      attempts: 'Tentatives',
      pipelineCod: 'COD en cours',
      commune: 'Commune',
      customers: 'Clients',
      customer: 'Client',
      city: 'Ville',
      submitted: 'Soumises',
      paidRevenue: 'Chiffre payé',
      contribution: 'Contribution',
      margin: 'Marge',
      postedOrders: 'Commandes publiées',
      paidOrders: 'Commandes payées',
      returnedOrders: 'Commandes retournées',
      costCoverage: 'Couverture des coûts',
      medianDelivery: 'Livraison médiane',
      units: 'Unités',
      economicControls: 'Paramètres économiques',
      period: 'Période',
      returnPercent: 'Retour %',
      blankFieldsDefer: 'Les champs vides utilisent séparément la source automatique.',
      orders: 'commandes',
      terminal: 'terminaux',
      eligible: 'éligibles',
      resolved: 'résolus',
      postingCohorts: 'cohortes de publication',
      terminalOrders: 'commandes terminales',
      metaInsightsSynchronized: 'Données Meta synchronisées.',
      googleSearchSynchronized: 'Données Google Search synchronisées.',
      syncFailed: 'Échec de la synchronisation.',
      syncGoogle: 'Synchroniser Google',
      played: 'Lectures',
      completed: 'Terminées',
      outcomeWindow: 'fenêtre de résultat',
      events: 'événements',
      unavailable: 'indisponible',
      failed: 'en échec',
      noEvent: 'Aucun événement',
      rawEventWindow: 'fenêtre des événements bruts',
      empty: '(vide)',
      zeroResultsShort: 'sans résultat',
      samples: 'échantillons',
      poor: 'médiocres',
      sessions: 'sessions',
      clicks: 'clics',
      position: 'position',
      rankingPages: 'pages classées',
      brand: 'marque',
      discovery: 'découverte',
      nearPageOne: 'Près de la première page',
      ctrGap: 'Écart de CTR',
      contentGap: 'Contenu manquant',
      searchAppearance: 'Apparence dans la recherche',
      urls: 'URL',
      warnings: 'avertissements',
      downloaded: 'téléchargé',
      noUrlsInspected: 'Aucune URL inspectée',
      pagesNeedReview: 'pages à examiner',
      noActionableIssue: 'Aucun problème exploitable dans l’échantillon actuel',
      openPublicPage: 'Ouvrir la page publique',
      searchProduct: 'Rechercher un produit, SKU ou une catégorie',
      above: 'Au-dessus',
      below: 'En dessous',
      insufficientProductOutcomes:
        'Pas assez de résultats produit résolus pour une comparaison fiable.',
      noSku: 'Sans SKU',
      uncategorized: 'Sans catégorie',
      metaReportedRegions: 'Régions déclarées par Meta',
      aggregateMediaGeography: 'Géographie média agrégée · non reliée aux wilayas clients',
      untracked: 'non suivies',
      provider: 'transporteur',
      secondOrderConversion: 'Conversion vers la deuxième commande',
      exactMetaAssociations: 'Associations Meta exactes',
      unknownCampaign: 'Campagne inconnue',
      unknownAdSet: 'Ensemble publicitaire inconnu',
      noExactAdAssociation: 'Aucune association exacte par ID publicitaire sur cette période.',
      periodChange: 'Évolution de la période',
      assumptionsSaved: 'Hypothèses enregistrées.',
      operatingCostUpdated: 'Coût d’exploitation mis à jour.',
      operatingCostAdded: 'Coût d’exploitation ajouté.',
      operatingCostRemoved: 'Coût d’exploitation supprimé.',
      dailyOverrideSaved: 'Ajustement quotidien enregistré.',
      dailyValuesReset: 'Valeurs quotidiennes revenues aux sources automatiques.',
      cpmEur: 'CPM EUR',
      analyticsRange: 'Période analytique',
      analyticsGrain: 'Granularité analytique',
      startDate: 'Date de début',
      endDate: 'Date de fin',
      analyticsRequestFailed: 'Échec de la requête analytique.',
      productViewSessions: 'Sessions avec vue produit',
      cartSessions: 'Sessions avec panier',
      checkoutSessions: 'Sessions de paiement',
      submittedOrderSessions: 'Sessions avec commande soumise',
      nextSevenDayModel: 'Modèle des 7 prochains jours',
    },
    modes: {
      projected: 'Projeté',
      realized: 'Payé réel',
      cumulative: 'Cumulé',
      daily: 'Quotidien',
      campaign: 'Campagnes',
      adset: 'Ensembles',
      ad: 'Publicités',
    },
    cashStages: {
      submitted: 'Soumises · non confirmées',
      confirmed: 'Confirmées · non publiées',
      inTransit: 'En transit',
      deliveredAwaitingCollection: 'Livré · collecte en attente',
      collectedAwaitingPayout: 'Encaissé · paiement en attente',
      paymentReady: 'Paiement prêt',
      paid: 'Payé et archivé',
    },
    fulfillmentPhases: {
      paid: 'Payées',
      return: 'Retournées',
      cancelled: 'Annulées',
      cash: 'Paiement en attente',
      delivery: 'En livraison',
      transit: 'En transit',
      ready: 'Prêtes à expédier',
      exception: 'À examiner',
      untracked: 'Non suivies',
    },
    expectedToPost: 'devraient être publiées',
    returnCopy: {
      planning: 'Taux de planification',
      mature: 'Observé mature',
      terminal: 'Tous les terminaux',
      useMature: 'Utiliser le taux mature',
      useTerminal: 'Utiliser les terminaux',
      caveat:
        'L’historique observé est une preuve. Il ne change jamais le taux de planification sans votre choix.',
    },
    assumptions: {
      fx: 'Taux EUR → DZD',
      defaultReturn: 'Taux de retour par défaut',
      restFrom: 'Repos vendredi actif depuis',
      newCost: 'Ajouter un coût',
      monthly: 'Mensuel',
      once: 'Ponctuel',
      amount: 'Montant DZD',
      start: 'Date de début',
      end: 'Date de fin (optionnel)',
      newOverride: 'Modifier la journée',
      gross: 'Profit brut DZD',
      confirmed: 'Commandes confirmées',
      returnRate: 'Taux de retour %',
      notes: 'Note opérateur',
      automatic: 'Automatique',
      manual: 'Manuel',
      missing: 'Absent',
    },
  },
  ar: {
    loading: 'جارٍ تحديث العرض…',
    updated: 'آخر تحديث',
    refresh: 'تحديث',
    apply: 'تطبيق',
    cancel: 'إلغاء',
    close: 'إغلاق',
    save: 'حفظ',
    delete: 'حذف',
    reset: 'إعادة للوضع التلقائي',
    export: 'تصدير CSV',
    syncMeta: 'مزامنة نطاق Meta',
    syncing: 'جارٍ المزامنة…',
    inspect: 'تفاصيل',
    compare: 'مقارنة',
    previousPeriod: 'مقارنة بالفترة السابقة',
    noComparison: 'لا توجد فترة سابقة',
    noData: 'لا توجد بيانات موثوقة لهذا الاختيار.',
    partialPeriod: 'فترة مفتوحة',
    exactRows: 'القيم الدقيقة',
    sourceHealth: 'مصادر البيانات',
    sourceNote: 'التغطية جزء من المقياس وليست ملاحظة جانبية.',
    ranges: {
      '7d': '7 أيام',
      '14d': '14 يومًا',
      '30d': '30 يومًا',
      '90d': '90 يومًا',
      year: 'السنة',
      all: 'الكل',
      custom: 'مخصص',
    },
    grains: { auto: 'تلقائي', day: 'يومي', week: 'أسابيع الجمعة', month: 'شهري' },
    metrics: {
      trueProfit: 'الربح الحقيقي',
      profitX: 'مضاعف الربح',
      adjustedProfit: 'الربح المعدل',
      automaticPaidProfit: 'ربح الطلبات المدفوعة',
      paidProfitCoverage: 'تغطية تكلفة الطلبات المدفوعة',
      adCost: 'تكلفة Meta',
      postedOrders: 'الطلبات المرسلة',
      postedUnits: 'الوحدات المرسلة',
      paidUnits: 'الوحدات المدفوعة',
      costPerPosted: 'تكلفة / مرسلة',
      costPerDelivered: 'تكلفة / مسلمة',
      costPerPaid: 'تكلفة / مدفوعة',
      submittedOrders: 'الطلبات المسجلة',
      paidOrders: 'الطلبات المدفوعة',
      storefrontConversion: 'تحويل المتجر',
      impressions: 'مرات الظهور',
      outboundClicks: 'النقرات الصادرة',
      landingPageViews: 'زيارات الهبوط',
      activeShipments: 'الشحنات النشطة',
      observedReturnRate: 'نسبة الإرجاع الناضجة',
      sessions: 'الجلسات',
      engagementRate: 'التفاعل',
      purchases: 'الطلبات المسجلة',
      conversionRate: 'التحويل',
      errorRate: 'نسبة الأخطاء',
      returningJourneys: 'الزيارات المتكررة',
      productProfit: 'مرجع ربح التسوية',
      unitsSold: 'الوحدات المباعة',
      customers: 'العملاء',
      repeatRate: 'نسبة التكرار',
      activeMonthlyBurn: 'التكلفة الشهرية',
      periodOperatingCost: 'تكاليف الفترة',
      manualOverrideDays: 'أيام معدلة',
      projectedCoverage: 'تغطية التكلفة',
      searchClicks: 'نقرات Google',
      searchImpressions: 'مرات الظهور في البحث',
      searchCtr: 'نسبة النقر',
      averagePosition: 'متوسط الترتيب',
    },
    sections: {
      trajectory: 'مسار النشاط',
      signals: 'قائمة المتابعة',
      commerceFunnel: 'نضج الطلبات',
      cashPipeline: 'مسار السيولة',
      paidEconomics: 'اقتصاد الدفع التلقائي',
      reconciliation: 'مرجع التسوية',
      forecast: 'النظرة المستقبلية',
      moneyPerformance: 'الأداء المالي',
      weeklyEconomics: 'أسابيع تبدأ الجمعة',
      economicsLedger: 'السجل المالي',
      profitEfficiency: 'كفاءة الربح',
      creativeFatigue: 'إجهاد الإعلانات',
      creativeResponse: 'استجابة المحتوى',
      paidFunnel: 'قمع الإعلانات',
      hierarchy: 'هيكل الحملات',
      trackingHealth: 'سلامة التتبع',
      deliveryPipeline: 'مسار التوصيل',
      shipmentStates: 'حالات الشحن',
      exceptionQueue: 'قائمة الاستثناءات',
      cycleTime: 'زمن الدورة',
      attempts: 'المحاولات والنتيجة',
      cohorts: 'أفواج الطلبات المرسلة',
      siteTrend: 'اتجاه المتجر',
      searchTrend: 'الطلب عبر البحث',
      searchOpportunities: 'قائمة الفرص',
      searchPages: 'ظهور صفحات الهبوط',
      searchMix: 'مزيج الاكتشاف',
      indexHealth: 'صحة الفهرسة',
      siteFunnel: 'قمع المتجر',
      paths: 'المسارات الحديثة',
      searches: 'طلب البحث',
      landingPages: 'صفحات الهبوط',
      experience: 'جودة التجربة',
      products: 'ذكاء المنتجات',
      basketPairs: 'منتجات تشترى معًا',
      geography: 'المناطق والتوصيل',
      customerBase: 'قاعدة العملاء',
      planningReturns: 'نسبة الإرجاع المخططة',
      operatingCosts: 'تكاليف التشغيل',
      dailyOverrides: 'التعديلات اليومية',
      formula: 'المعادلة الأساسية',
      automationEvidence: 'الأتمتة مقابل التسويات',
    },
    sources: {
      orders: 'الطلبات',
      ecotrack: 'EcoTrack',
      meta: 'Meta',
      storefront: 'المتجر',
      searchConsole: 'بحث Google',
      settlements: 'التسويات',
      assumptions: 'افتراضات يدوية',
    },
    sourceStates: {
      live: 'مباشر',
      current: 'حالي',
      lagged: 'متأخر',
      manual: 'يدوي',
      partial: 'جزئي',
      missing: 'مفقود',
    },
    signalLabels: {
      belowBreakEven: 'مضاعف الربح دون نقطة التعادل',
      aboveBreakEven: 'مضاعف الربح فوق نقطة التعادل',
      returnAssumptionGap: 'المرتجعات المرصودة تختلف عن التخطيط',
      costCoverageGap: 'بيانات تكلفة الشراء غير مكتملة',
      fridayPending: 'إنفاق الجمعة ينتظر الترحيل',
      activePipeline: 'طلبات ما زالت في مسار التوصيل',
    },
    warningLabels: {
      sourceMissing: 'مصدر مفقود لهذه الفترة',
      sourcePartial: 'مصدر يغطي جزءًا فقط من الفترة',
      projectedCostCoverage: 'الربح المتوقع يستخدم هامشًا احتياطيًا بنسبة 30٪',
      pendingFridayRollforward: 'إنفاق Meta للجمعة ينتظر الترحيل',
      pathRetentionPartial: 'تفاصيل المسارات محدودة بمدة الاحتفاظ بالأحداث',
      searchDetailCoverage: 'تفاصيل الاستعلام والصفحة محدودة بخصوصية Google',
    },
    columns: {
      date: 'التاريخ',
      value: 'القيمة',
      status: 'الحالة',
      orders: 'الطلبات',
      spend: 'الإنفاق',
      profit: 'الربح',
      trueProfit: 'الربح الحقيقي',
      profitX: 'مضاعف الربح',
      operatingCost: 'تكاليف التشغيل',
      grossProfit: 'الربح الخام',
      adjustedProfit: 'الربح المعدل',
      adCost: 'تكلفة الإعلان',
      netProfit: 'صافي الربح',
      coverage: 'التغطية',
      name: 'الاسم',
      campaign: 'الحملة',
      impressions: 'الظهور',
      ctr: 'CTR',
      outboundCtr: 'CTR الصادر',
      cpm: 'CPM',
      landingViews: 'زيارات الهبوط',
      videoCompletion: 'اكتمال الفيديو',
      watchTime: 'متوسط المشاهدة',
      ranking: 'الترتيب',
      confirmed: 'مؤكدة',
      posted: 'مرسلة',
      paid: 'مدفوعة',
      returned: 'مرتجعة',
      costPerPosted: 'تكلفة / مرسلة',
      share: 'الحصة',
      stale: 'متوقفة >48س',
      age: 'متوسط العمر',
      p50: 'الوسيط',
      p75: 'P75',
      p90: 'P90',
      sample: 'العينة',
      sessions: 'الجلسات',
      conversion: 'التحويل',
      views: 'المشاهدات',
      carts: 'السلات',
      revenue: 'الإيراد',
      units: 'الوحدات',
      margin: 'الهامش',
      category: 'الفئة',
      brand: 'العلامة',
      first: 'الأول',
      second: 'الثاني',
      repeat: 'التكرار',
      source: 'المصدر',
      note: 'ملاحظة',
      query: 'عبارة البحث',
      page: 'الصفحة',
      clicks: 'النقرات',
      position: 'الترتيب',
      potential: 'نقرات محتملة',
      device: 'الجهاز',
      country: 'الدولة',
    },
    labels: {
      ecoTrackFee: 'رسوم EcoTrack',
      paidCod: 'تحصيل مدفوع',
      estimatedFees: 'الرسوم المقدرة',
      netRecovered: 'الصافي المحصل',
      cod: 'التحصيل',
      fees: 'الرسوم',
      providerCod: 'تحصيل شركة التوصيل',
      profitMaturation: 'نضج الربح',
      projectedTrueProfit: 'الربح الحقيقي المتوقع',
      deliveredTrueProfit: 'الربح الحقيقي المسلّم',
      paidTrueProfit: 'الربح الحقيقي المدفوع',
      postingWeek: 'أسبوع النشر',
      posted: 'منشورة',
      delivered: 'مسلّمة',
      paid: 'مدفوعة',
      projected: 'متوقع',
      paidProfit: 'الربح المدفوع',
      variance: 'الفرق',
      maturity: 'النضج',
      open: 'مفتوح',
      upper: 'الحد الأعلى',
      lower: 'الحد الأدنى',
      beforeReturns: 'قبل المرتجعات',
      afterReturns: 'بعد المرتجعات',
      playRate: 'معدل التشغيل',
      completion: 'الإكمال',
      averageWatch: 'متوسط المشاهدة',
      outboundCtr: 'معدل النقر الخارجي',
      confirmationRate: 'معدل التأكيد',
      clickToPage: 'النقرة ← الصفحة',
      metaPurchases: 'مشتريات Meta',
      firstPartyOrders: 'طلبات الطرف الأول',
      exactAdIdCoverage: 'تغطية معرّفات الإعلانات الدقيقة',
      outcomeMaturity: 'نضج النتائج',
      campaignMaturation: 'نضج الحملات',
      costPerPosted: 'التكلفة / منشورة',
      costPerDelivered: 'التكلفة / مسلّمة',
      costPerPaid: 'التكلفة / مدفوعة',
      metaSpend: 'إنفاق Meta',
      adCostDzd: 'تكلفة الإعلان DZD',
      outcomeWindowCost: 'تكلفة نافذة النتائج',
      outcomeSpendCoverage: 'تغطية إنفاق النتائج',
      impressions: 'مرات الظهور',
      outboundClicks: 'النقرات الخارجية',
      uniqueOutbound: 'النقرات الخارجية الفريدة',
      landingViews: 'مشاهدات صفحة الوصول',
      landingViewRate: 'معدل مشاهدة صفحة الوصول',
      videoPlays: 'تشغيلات الفيديو',
      videoCompletion: 'إكمال الفيديو',
      qualityRanking: 'ترتيب الجودة',
      engagementRanking: 'ترتيب التفاعل',
      conversionRanking: 'ترتيب التحويل',
      bricOrders: 'طلبات Bric',
      confirmed: 'مؤكدة',
      returned: 'مرتجعة',
      projectedProfitX: 'الربح × المتوقع',
      paidProfitX: 'الربح × المدفوع',
      profitCoverage: 'تغطية الربح',
      manualModelInput: 'مدخل يدوي للنموذج',
      active: 'نشطة',
      errors: 'أخطاء',
      productViewToCartSessions: 'عرض المنتج ← السلة',
      checkoutToSubmittedOrder: 'الدفع ← الطلب المرسل',
      from: 'من',
      to: 'إلى',
      aiAssistedShopping: 'تسوق بمساعدة الذكاء الاصطناعي',
      opens: 'مرات الفتح',
      messages: 'الرسائل',
      resultClicks: 'نقرات النتائج',
      influencedOrders: 'الطلبات المتأثرة',
      opportunity: 'الفرصة',
      searchLandingPagesDescription:
        'صفحات الوصول كما يراها Google. اختر صفًا لمراجعة عبارات البحث التي تمنحها الظهور.',
      queries: 'عبارات البحث',
      devices: 'الأجهزة',
      countries: 'الدول',
      sitemap: 'خريطة الموقع',
      inspectedSample: 'العينة المفحوصة',
      searchOpportunityEvidence: 'أدلة فرصة البحث',
      currentCtr: 'معدل النقر الحالي',
      comparableCtr: 'معدل النقر المقارن',
      googleLandingPageEvidence: 'أدلة Google لصفحة الوصول',
      productViews: 'مشاهدات المنتج',
      terminalPaid: 'مدفوعة نهائيًا',
      paidReturned: 'مدفوعة / مرتجعة',
      stillActive: 'ما زالت نشطة',
      scatterViews: 'المشاهدات ←',
      scatterPaidOutcome: 'النتيجة المدفوعة ↑',
      bubbleResolvedOrders: 'الفقاعة · الطلبات المحسومة',
      terminalPaidRate: 'معدل الدفع النهائي',
      postedUnits: 'الوحدات المنشورة',
      projectedContribution: 'المساهمة المتوقعة',
      delivery: 'التوصيل',
      wilaya: 'الولاية',
      attempts: 'المحاولات',
      pipelineCod: 'التحصيل الجاري',
      commune: 'البلدية',
      customers: 'العملاء',
      customer: 'العميل',
      city: 'المدينة',
      submitted: 'مرسلة',
      paidRevenue: 'الإيراد المدفوع',
      contribution: 'المساهمة',
      margin: 'الهامش',
      postedOrders: 'الطلبات المنشورة',
      paidOrders: 'الطلبات المدفوعة',
      returnedOrders: 'الطلبات المرتجعة',
      costCoverage: 'تغطية التكلفة',
      medianDelivery: 'وسيط مدة التوصيل',
      units: 'الوحدات',
      economicControls: 'الإعدادات الاقتصادية',
      period: 'الفترة',
      returnPercent: 'الإرجاع %',
      blankFieldsDefer: 'تعود الحقول الفارغة كلٌ على حدة إلى المصدر التلقائي.',
      orders: 'طلبات',
      terminal: 'نهائية',
      eligible: 'مؤهلة',
      resolved: 'محسومة',
      postingCohorts: 'مجموعات النشر',
      terminalOrders: 'طلبات نهائية',
      metaInsightsSynchronized: 'تمت مزامنة بيانات Meta.',
      googleSearchSynchronized: 'تمت مزامنة بيانات بحث Google.',
      syncFailed: 'فشلت المزامنة.',
      syncGoogle: 'مزامنة Google',
      played: 'تم تشغيله',
      completed: 'مكتمل',
      outcomeWindow: 'نافذة النتائج',
      events: 'أحداث',
      unavailable: 'غير متاح',
      failed: 'فاشل',
      noEvent: 'لا حدث',
      rawEventWindow: 'نافذة الأحداث الخام',
      empty: '(فارغ)',
      zeroResultsShort: 'بدون نتائج',
      samples: 'عينات',
      poor: 'ضعيفة',
      sessions: 'جلسات',
      clicks: 'نقرات',
      position: 'الترتيب',
      rankingPages: 'صفحات مرتبة',
      brand: 'علامة',
      discovery: 'اكتشاف',
      nearPageOne: 'قريبة من الصفحة الأولى',
      ctrGap: 'فجوة معدل النقر',
      contentGap: 'فجوة محتوى',
      searchAppearance: 'مظهر البحث',
      urls: 'روابط',
      warnings: 'تحذيرات',
      downloaded: 'آخر تنزيل',
      noUrlsInspected: 'لم يتم فحص أي رابط',
      pagesNeedReview: 'صفحات تحتاج مراجعة',
      noActionableIssue: 'لا توجد مشكلة قابلة للإجراء في العينة الحالية',
      openPublicPage: 'فتح الصفحة العامة',
      searchProduct: 'ابحث عن منتج أو SKU أو فئة',
      above: 'أعلى',
      below: 'أدنى',
      insufficientProductOutcomes: 'لا توجد نتائج منتجات محسومة كافية لمقارنة موثوقة.',
      noSku: 'بدون SKU',
      uncategorized: 'بدون فئة',
      metaReportedRegions: 'المناطق المبلّغ عنها من Meta',
      aggregateMediaGeography: 'جغرافيا إعلامية مجمعة · غير مرتبطة بولايات العملاء',
      untracked: 'غير متتبعة',
      provider: 'شركة التوصيل',
      secondOrderConversion: 'التحويل إلى الطلب الثاني',
      exactMetaAssociations: 'روابط Meta الدقيقة',
      unknownCampaign: 'حملة غير معروفة',
      unknownAdSet: 'مجموعة إعلانية غير معروفة',
      noExactAdAssociation: 'لا يوجد ارتباط دقيق بمعرّف إعلان في هذا النطاق.',
      periodChange: 'تغير الفترة',
      assumptionsSaved: 'تم حفظ الافتراضات.',
      operatingCostUpdated: 'تم تحديث تكلفة التشغيل.',
      operatingCostAdded: 'تمت إضافة تكلفة التشغيل.',
      operatingCostRemoved: 'تم حذف تكلفة التشغيل.',
      dailyOverrideSaved: 'تم حفظ التعديل اليومي.',
      dailyValuesReset: 'عادت القيم اليومية إلى المصادر التلقائية.',
      cpmEur: 'CPM EUR',
      analyticsRange: 'نطاق التحليلات',
      analyticsGrain: 'تجميع التحليلات',
      startDate: 'تاريخ البدء',
      endDate: 'تاريخ النهاية',
      analyticsRequestFailed: 'فشل طلب التحليلات.',
      productViewSessions: 'جلسات مشاهدة المنتج',
      cartSessions: 'جلسات السلة',
      checkoutSessions: 'جلسات الدفع',
      submittedOrderSessions: 'جلسات الطلبات المرسلة',
      nextSevenDayModel: 'نموذج الأيام السبعة القادمة',
    },
    modes: {
      projected: 'متوقع',
      realized: 'مدفوع فعلي',
      cumulative: 'تراكمي',
      daily: 'يومي',
      campaign: 'الحملات',
      adset: 'المجموعات',
      ad: 'الإعلانات',
    },
    cashStages: {
      submitted: 'مُرسلة · غير مؤكدة',
      confirmed: 'مؤكدة · غير منشورة',
      inTransit: 'قيد النقل',
      deliveredAwaitingCollection: 'تم التسليم · بانتظار التحصيل',
      collectedAwaitingPayout: 'تم التحصيل · بانتظار الدفع',
      paymentReady: 'الدفع جاهز',
      paid: 'مدفوع ومؤرشف',
    },
    fulfillmentPhases: {
      paid: 'مدفوعة',
      return: 'مرتجعة',
      cancelled: 'ملغاة',
      cash: 'بانتظار الدفع',
      delivery: 'قيد التوصيل',
      transit: 'قيد النقل',
      ready: 'جاهزة للشحن',
      exception: 'تحتاج مراجعة',
      untracked: 'غير متتبعة',
    },
    expectedToPost: 'متوقع نشرها',
    returnCopy: {
      planning: 'نسبة التخطيط',
      mature: 'المرصود الناضج',
      terminal: 'كل النتائج النهائية',
      useMature: 'استخدام النسبة الناضجة',
      useTerminal: 'استخدام كل النتائج',
      caveat: 'يظهر التاريخ المرصود كدليل ولا يغيّر نسبة التخطيط إلا باختيارك.',
    },
    assumptions: {
      fx: 'سعر EUR → DZD',
      defaultReturn: 'نسبة الإرجاع الافتراضية',
      restFrom: 'بدء راحة الجمعة',
      newCost: 'إضافة تكلفة',
      monthly: 'شهري',
      once: 'مرة واحدة',
      amount: 'المبلغ DZD',
      start: 'تاريخ البدء',
      end: 'تاريخ النهاية (اختياري)',
      newOverride: 'تعديل اليوم',
      gross: 'الربح الخام DZD',
      confirmed: 'الطلبات المؤكدة',
      returnRate: 'نسبة الإرجاع %',
      notes: 'ملاحظة المشغل',
      automatic: 'تلقائي',
      manual: 'يدوي',
      missing: 'مفقود',
    },
  },
} as const;

export type Analytics2Copy = (typeof analytics2Copy)['en'];

export function getAnalytics2Copy(locale: string): Analytics2Copy {
  const key = locale.startsWith('ar') ? 'ar' : locale.startsWith('fr') ? 'fr' : 'en';
  return analytics2Copy[key] as unknown as Analytics2Copy;
}
