'use client';
import { type AssetsWorkspaceCopy } from '../assets-editor-panel';

export type AssetsWorkspaceView = 'banners' | 'groups' | 'cards';

const copy: Record<
  'en' | 'fr' | 'ar',
  AssetsWorkspaceCopy & { refreshFailed: string; retry: string }
> = {
  en: {
    title: 'Assets',
    banners: 'Banners',
    groups: 'Featured groups',
    cards: 'Product cards',
    landingPages: 'Landing pages',
    create: 'Create',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    save: 'Save',
    close: 'Close',
    active: 'Active',
    inactive: 'Inactive',
    actions: 'Actions',
    moveUp: 'Move up',
    moveDown: 'Move down',
    modified: 'Modified',
    noRecords: 'No records yet.',
    confirmDelete: 'Delete this record? This cannot be undone.',
    product: 'Product',
    order: 'Order',
    bannerTitle: 'Title',
    bannerTitleAr: 'Arabic title',
    landscape: 'Landscape image',
    portrait: 'Portrait image',
    groupName: 'Group name',
    groupNameAr: 'Arabic group name',
    cta: 'CTA text',
    ctaAr: 'Arabic CTA text',
    link: 'CTA link',
    recommendationPriority: 'Prioritize in product recommendations',
    products: 'Products',
    brands: 'Brands',
    categories: 'Categories',
    noSelection: 'No selection',
    cardTitleFr: 'French title',
    cardTitleAr: 'Arabic title',
    cardDescriptionFr: 'French description',
    cardDescriptionAr: 'Arabic description',
    characteristicsFr: 'French characteristics · one per line',
    characteristicsAr: 'Arabic characteristics · one per line',
    characteristicsRequirement: 'Enter at least three features in French and Arabic, one per line.',
    productSearch: 'Search products',
    productEmpty: 'No products match.',
    selected: 'Selected products',
    remove: 'Remove',
    validation: 'Review the entered information.',
    mutationFailed: 'The change could not be saved.',
    refreshFailed: 'Saved. The list could not be refreshed.',
    retry: 'Refresh list',
  },
  fr: {
    title: 'Ressources',
    banners: 'Bannières',
    groups: 'Groupes vedettes',
    cards: 'Cartes produit',
    landingPages: 'Pages d’atterrissage',
    create: 'Créer',
    edit: 'Modifier',
    delete: 'Supprimer',
    cancel: 'Annuler',
    save: 'Enregistrer',
    close: 'Fermer',
    active: 'Actif',
    inactive: 'Inactif',
    actions: 'Actions',
    moveUp: 'Monter',
    moveDown: 'Descendre',
    modified: 'Modifié',
    noRecords: 'Aucun élément.',
    confirmDelete: 'Supprimer cet élément ? Cette action est définitive.',
    product: 'Produit',
    order: 'Ordre',
    bannerTitle: 'Titre',
    bannerTitleAr: 'Titre arabe',
    landscape: 'Image horizontale',
    portrait: 'Image verticale',
    groupName: 'Nom du groupe',
    groupNameAr: 'Nom arabe',
    cta: 'Texte du CTA',
    ctaAr: 'CTA arabe',
    link: 'Lien du CTA',
    recommendationPriority: 'Prioriser dans les recommandations produits',
    products: 'Produits',
    brands: 'Marques',
    categories: 'Catégories',
    noSelection: 'Aucune sélection',
    cardTitleFr: 'Titre français',
    cardTitleAr: 'Titre arabe',
    cardDescriptionFr: 'Description française',
    cardDescriptionAr: 'Description arabe',
    characteristicsFr: 'Caractéristiques françaises · une par ligne',
    characteristicsAr: 'Caractéristiques arabes · une par ligne',
    characteristicsRequirement:
      'Saisissez au moins trois caractéristiques en français et en arabe, une par ligne.',
    productSearch: 'Rechercher des produits',
    productEmpty: 'Aucun produit correspondant.',
    selected: 'Produits sélectionnés',
    remove: 'Retirer',
    validation: 'Vérifiez les informations saisies.',
    mutationFailed: 'La modification n’a pas pu être enregistrée.',
    refreshFailed: 'Enregistré. La liste n’a pas pu être actualisée.',
    retry: 'Actualiser la liste',
  },
  ar: {
    title: 'المحتوى المرئي',
    banners: 'اللافتات',
    groups: 'المجموعات المميزة',
    cards: 'بطاقات المنتجات',
    landingPages: 'صفحات الهبوط',
    create: 'إنشاء',
    edit: 'تعديل',
    delete: 'حذف',
    cancel: 'إلغاء',
    save: 'حفظ',
    close: 'إغلاق',
    active: 'نشط',
    inactive: 'غير نشط',
    actions: 'الإجراءات',
    moveUp: 'تحريك للأعلى',
    moveDown: 'تحريك للأسفل',
    modified: 'آخر تعديل',
    noRecords: 'لا توجد عناصر بعد.',
    confirmDelete: 'حذف هذا العنصر؟ لا يمكن التراجع عن ذلك.',
    product: 'المنتج',
    order: 'الترتيب',
    bannerTitle: 'العنوان',
    bannerTitleAr: 'العنوان العربي',
    landscape: 'الصورة الأفقية',
    portrait: 'الصورة العمودية',
    groupName: 'اسم المجموعة',
    groupNameAr: 'الاسم العربي',
    cta: 'نص الدعوة',
    ctaAr: 'نص الدعوة العربي',
    link: 'رابط الدعوة',
    recommendationPriority: 'إعطاء الأولوية في توصيات المنتجات',
    products: 'المنتجات',
    brands: 'العلامات',
    categories: 'الفئات',
    noSelection: 'لا يوجد اختيار',
    cardTitleFr: 'العنوان الفرنسي',
    cardTitleAr: 'العنوان العربي',
    cardDescriptionFr: 'الوصف الفرنسي',
    cardDescriptionAr: 'الوصف العربي',
    characteristicsFr: 'الخصائص الفرنسية · واحدة في كل سطر',
    characteristicsAr: 'الخصائص العربية · واحدة في كل سطر',
    characteristicsRequirement: 'أدخل ثلاث ميزات على الأقل بالفرنسية والعربية، كل ميزة في سطر.',
    productSearch: 'البحث في المنتجات',
    productEmpty: 'لا توجد منتجات مطابقة.',
    selected: 'المنتجات المختارة',
    remove: 'إزالة',
    validation: 'راجع المعلومات المدخلة.',
    mutationFailed: 'تعذّر حفظ التغيير.',
    refreshFailed: 'تم الحفظ. تعذّر تحديث القائمة.',
    retry: 'تحديث القائمة',
  },
};

export function getAssetsWorkspaceCopy(locale: string) {
  return copy[locale === 'ar' || locale === 'fr' ? locale : 'en'];
}
